
#include <stdio.h>
#include "cipcommon.h"

//#define VID(x)      // nothing
#define VID(x)      x,

// Translate Vendor IDs
static const struct VendorRow {
    short       id;
    const char* name;
} vendors[] = {
    {   VID(0)      "Reserved" },
    {   VID(1)      "Rockwell Automation/Allen-Bradley" },
    {   VID(2)      "Reserved" },
    {   VID(3)      "Honeywell International Inc." },
    {   VID(4)      "Parker Hannifin Corporation" },
    {   VID(5)      "Reserved" },
    {   VID(6)      "Reserved" },
    {   VID(7)      "SMC Corporation" },
    {   VID(8)      "Molex Incorporated" },
    {   VID(9)      "Western Reserve Controls Inc." },
    {   VID(10)     "Advanced Micro Controls Inc. (AMCI)" },
    {   VID(11)     "Reserved" },
    {   VID(12)     "Banner Engineering Corporation" },
    {   VID(13)     "Reserved" },
    {   VID(14)     "Reserved" },
    {   VID(16)     "Daniel Woodhead Co." },
    {   VID(17)     "Reserved" },
    {   VID(18)     "Reserved" },
    {   VID(19)     "Reserved" },
    {   VID(20)     "Huron Net Works" },
    {   VID(21)     "Belden Deutschland GmbH" },
    {   VID(22)     "Online Development, Inc. (OLDI)" },
    {   VID(23)     "Reserved" },
    {   VID(24)     "ODVA" },
    {   VID(25)     "Reserved" },
    {   VID(26)     "Festo" },
    {   VID(27)     "Reserved" },
    {   VID(28)     "Reserved" },
    {   VID(30)     "Reserved" },
    {   VID(31)     "Reserved" },
    {   VID(33)     "Reserved" },
    {   VID(34)     "Reserved" },
    {   VID(35)     "Reserved" },
    {   VID(36)     "MKS Instruments, Inc." },
    {   VID(37)     "Yaskawa Electric America formerly Magnetek Drives" },
    {   VID(38)     "Reserved" },
    {   VID(39)     "AVG Automation (Uticor)" },
    {   VID(40)     "WAGO Corporation" },
    {   VID(41)     "Celerity, Inc." },
    {   VID(42)     "IMI Norgren Limited" },
    {   VID(43)     "BALLUFF" },
    {   VID(44)     "Yaskawa America, Inc." },
    {   VID(45)     "Eurotherm by Schneider Electric" },
    {   VID(46)     "ABB, Inc." },
    {   VID(47)     "Omron Corporation" },
    {   VID(48)     "TURCK" },
    {   VID(49)     "Reserved" },
    {   VID(50)     "Real Time Automation" },
    {   VID(51)     "Reserved" },
    {   VID(52)     "ASCO Numatics" },
    {   VID(53)      "Reserved" },
    {   VID(54)     "Reserved" },
    {   VID(55)     "Reserved" },
    {   VID(56)     "Softing" },
    {   VID(57)     "Pepperl+Fuchs " },
    {   VID(58)     "Spectrum Controls, Inc." },
    {   VID(59)     "Reserved" },
    {   VID(60)     "Applied Motion Products, Inc." },
    {   VID(61)     "Reserved" },
    {   VID(62)     "Reserved" },
    {   VID(63)     "Reserved" },
    {   VID(64)     "Reserved" },
    {   VID(65)     "Reserved" },
    {   VID(66)     "Reserved" },
    {   VID(67)     "Reserved" },
    {   VID(68)     "Eaton Electrical" },
    {   VID(69)     "Reserved" },
    {   VID(70)     "Reserved" },
    {   VID(71)     "Toshiba Corporation" },
    {   VID(72)     "Control Technology Incorporated" },
    {   VID(73)     "Reserved" },
    {   VID(74)     "Hitachi, Ltd." },
    {   VID(75)     "ABB Robotics" },
    {   VID(76)     "NKE Corporation" },
    {   VID(77)     "Reserved" },
    {   VID(78)     "Reserved" },
    {   VID(79)     "Leviton" },
    {   VID(80)     "Reserved" },
    {   VID(81)     "Reserved" },
    {   VID(82)     "Mitsubishi Electric Automation, Inc." },
    {   VID(83)     "OPTO 22" },
    {   VID(84)     "Reserved" },
    {   VID(85)     "Reserved" },
    {   VID(86)     "Horner Electric" },
    {   VID(87)     "Buerkert Fluid Control Systems" },
    {   VID(88)     "Reserved" },
    {   VID(89)     "Industrial Indexing Systems, Inc." },
    {   VID(90)     "HMS Networks" },
    {   VID(91)     "Reserved" },
    {   VID(92)     "Helix Technology (Granville-Phillips)" },
    {   VID(93)     "Reserved" },
    {   VID(94)     "Advantech Corporation" },
    {   VID(95)     "Reserved" },
    {   VID(96)     "Reserved" },
    {   VID(97)     "Danfoss Drives A/S" },
    {   VID(98)     "Reserved" },
    {   VID(99)     "Reserved" },
    {   VID(100)    "AVENTICS" },
    {   VID(101)    "Reserved" },
    {   VID(102)    "SWCC Showa Cable Systems Co., Ltd." },
    {   VID(103)    "Reserved" },
    {   VID(104)    "Sharp Manufacturing Systems Corporation" },
    {   VID(105)    "Reserved" },
    {   VID(106)    "Reserved" },
    {   VID(107)    "Reserved" },
    {   VID(108)    "Beckhoff Automation" },
    {   VID(109)    "National Instruments" },
    {   VID(110)    "Mykrolis Corporation (Millipore)" },
    {   VID(111)    "Reserved" },
    {   VID(112)    "Reserved" },
    {   VID(113)    "Reserved" },
    {   VID(114)    "Reserved" },
    {   VID(115)    "Reserved" },
    {   VID(116)    "Temposonics, LLC" },
    {   VID(117)    "Reserved" },
    {   VID(119)    "EXOR Electronic R & D" },
    {   VID(120)    "Reserved" },
    {   VID(121)    "KUKA Deutschland GmbH" },
    {   VID(122)    "Reserved" },
    {   VID(123)    "Reserved" },
    {   VID(124)    "Reserved" },
    {   VID(125)    "Reserved" },
    {   VID(126)    "Reserved" },
    {   VID(127)    "Reserved" },
    {   VID(128)    "MAC Valves, Inc." },
    {   VID(129)    "AUMA Riester GmbH & Co. KG" },
    {   VID(130)    "JTEKT Corporation" },
    {   VID(131)    "Reserved" },
    {   VID(132)    "Reserved" },
    {   VID(133)    "Reserved" },
    {   VID(134)    "TR Electronic" },
    {   VID(135)    "UNIPULSE Corporation" },
    {   VID(136)    "Reserved" },
    {   VID(137)    "Reserved" },
    {   VID(138)    "Reserved" },
    {   VID(139)    "Reserved" },
    {   VID(140)    "Reserved" },
    {   VID(141)    "Kuramo Electric Co., Ltd." },
    {   VID(142)    "Reserved" },
    {   VID(143)    "Reserved" },
    {   VID(144)    "Leybold GmbH" },
    {   VID(145)    "Reserved" },
    {   VID(146)    "Reserved" },
    {   VID(147)    "Reserved" },
    {   VID(148)    "Reserved" },
    {   VID(149)    "Reserved" },
    {   VID(150)    "Melec Inc." },
    {   VID(152)    "Reserved" },
    {   VID(153)    "Watlow" },
    {   VID(154)    "Reserved" },
    {   VID(155)    "NADEX Co., Ltd" },
    {   VID(156)    "Ametek Automation & Process Technologies" },
    {   VID(157)    "Facts, Inc." },
    {   VID(158)    "Reserved" },
    {   VID(159)    "IDEC Corporation" },
    {   VID(160)    "Reserved" },
    {   VID(161)    "Mitsubishi Electric Corporation" },
    {   VID(162)    "HORIBA STEC, Co., Ltd." },
    {   VID(163)    "esd electronics gmbh" },
    {   VID(164)    "DAIHEN Corporation" },
    {   VID(165)    "Reserved" },
    {   VID(166)    "Reserved" },
    {   VID(168)    "Reserved" },
    {   VID(169)    "Hokuyo Automatic Co., Ltd." },
    {   VID(170)    "Pyramid Solutions, Inc." },
    {   VID(171)    "Denso Wave Incorporated" },
    {   VID(172)    "Reserved" },
    {   VID(173)    "Caterpillar, Inc." },
    {   VID(174)    "Reserved" },
    {   VID(175)    "Reserved" },
    {   VID(176)    "Red Lion " },
    {   VID(177)    "CANON ANELVA Corporation" },
    {   VID(178)    "Toyo Denki Seizo KK" },
    {   VID(179)    "Sanyo Denki Co., Ltd." },
    {   VID(180)    "Hitachi Metals, Ltd. (formerly Advanced Energy Japan K.K.)" },
    {   VID(181)    "Pilz GmbH & Co KG" },
    {   VID(182)    "Reserved" },
    {   VID(183)    "Reserved" },
    {   VID(184)    "M-SYSTEM Co., Ltd." },
    {   VID(185)    "Nissin Electric Co., Ltd." },
    {   VID(186)    "Hitachi Metals Ltd." },
    {   VID(187)    "Oriental Motor Co., Ltd" },
    {   VID(188)    "A&D Company Limited" },
    {   VID(189)    "Reserved" },
    {   VID(190)    "Reserved" },
    {   VID(191)    "Reserved" },
    {   VID(192)    "Reserved" },
    {   VID(193)    "Reserved" },
    {   VID(194)    "Reserved" },
    {   VID(195)    "Reserved" },
    {   VID(196)    "Reserved" },
    {   VID(197)    "XP Power LLC" },
    {   VID(198)    "Advanced Energy Industries, Inc." },
    {   VID(199)    "Reserved" },
    {   VID(200)    "Reserved" },
    {   VID(201)    "CKD Corporation" },
    {   VID(202)    "Reserved" },
    {   VID(203)    "Reserved" },
    {   VID(204)    "AuCom Electronics Ltd" },
    {   VID(205)    "Sinfonia Technology Co., Ltd." },
    {   VID(206)    "Reserved" },
    {   VID(207)    "Reserved" },
    {   VID(208)    "Reserved" },
    {   VID(209)    "Reserved" },
    {   VID(210)    "Reserved" },
    {   VID(211)    "Schenck Process" },
    {   VID(212)    "Reserved" },
    {   VID(213)    "Reserved" },
    {   VID(214)    "ASM Japan K.K." },
    {   VID(215)    "Reserved" },
    {   VID(216)    "Panasonic Industrial Devices SUNX Co., Ltd." },
    {   VID(217)    "Meidensha Corporation" },
    {   VID(218)    "Reserved" },
    {   VID(219)    "Reserved" },
    {   VID(220)    "NSD Co., Ltd." },
    {   VID(221)    "Reserved" },
    {   VID(222)    "Reserved" },
    {   VID(223)    "Reserved" },
    {   VID(224)    "Reserved" },
    {   VID(225)    "Reserved" },
    {   VID(226)    "Reserved" },
    {   VID(227)    "Reserved" },
    {   VID(228)    "Reserved" },
    {   VID(229)    "Reserved" },
    {   VID(230)    "NSD Corporation" },
    {   VID(231)    "Reserved" },
    {   VID(232)    "Reserved" },
    {   VID(233)    "Reserved" },
    {   VID(234)    "Reserved" },
    {   VID(235)    "Reserved" },
    {   VID(236)    "Reserved" },
    {   VID(237)    "Reserved" },
    {   VID(238)    "Reserved" },
    {   VID(239)    "Reserved" },
    {   VID(240)    "Reserved" },
    {   VID(241)    "Reserved" },
    {   VID(242)    "Reserved" },
    {   VID(243)    "Schneider Electric" },
    {   VID(244)    "Westlock Controls Corp." },
    {   VID(245)    "Reserved" },
    {   VID(246)    "Brooks Instrument" },
    {   VID(247)    "Reserved" },
    {   VID(248)    "Eaton Industries GmbH (formerly Moeller GmbH)" },
    {   VID(249)    "Reserved" },
    {   VID(250)    "Yokogawa Electric Corporation" },
    {   VID(251)    "Reserved" },
    {   VID(252)    "Omron Software Co., Ltd." },
    {   VID(253)    "EDWARDS" },
    {   VID(254)    "Reserved" },
    {   VID(255)    "Reserved" },
    {   VID(256)    "TURCK (formerly InterlinkBT)" },
    {   VID(257)    "Control Techniques PLC" },
    {   VID(258)    "Hardy Process Solutions" },
    {   VID(259)    "LS ELECTRIC" },
    {   VID(260)    "Reserved" },
    {   VID(261)    "Reserved" },
    {   VID(262)    "New Cosmos Electric Co., Ltd." },
    {   VID(263)    "Sense Sense Eletronica LTDA" },
    {   VID(264)    "Reserved" },
    {   VID(265)    "Reserved" },
    {   VID(266)    "Reserved" },
    {   VID(267)    "Patlite Corporation" },
    {   VID(268)    "Reserved" },
    {   VID(269)    "Reserved" },
    {   VID(270)    "Welding Technology Corporation" },
    {   VID(271)    "Reserved" },
    {   VID(272)    "Deutschmann Automation GmbH" },
    {   VID(273)    "Reserved" },
    {   VID(274)    "Bray International, Inc" },
    {   VID(275)    "Reserved" },
    {   VID(276)    "Reserved" },
    {   VID(277)    "Trio Motion Technology ltd" },
    {   VID(278)    "Reserved" },
    {   VID(279)    "Reserved" },
    {   VID(280)    "Spang Power Electronics" },
    {   VID(281)    "Reserved" },
    {   VID(282)    "Reserved" },
    {   VID(283)    "Hilscher GmbH" },
    {   VID(284)    "Reserved" },
    {   VID(285)    "Electronic Innovation, Inc. (Falter Engineering)" },
    {   VID(286)    "Reserved" },
    {   VID(287)    "Bosch Rexroth AG" },
    {   VID(288)    "Reserved" },
    {   VID(289)    "Reserved" },
    {   VID(290)    "Reserved" },
    {   VID(291)    "MTT Corporation" },
    {   VID(292)    "Reserved" },
    {   VID(293)    "Reserved" },
    {   VID(294)    "Reserved" },
    {   VID(295)    "Reserved" },
    {   VID(296)    "Reserved" },
    {   VID(297)    "Advanet Inc." },
    {   VID(298)    "Reserved" },
    {   VID(299)    "Reserved" },
    {   VID(300)    "Reserved" },
    {   VID(301)    "Reserved" },
    {   VID(302)    "Reserved" },
    {   VID(303)    "Reserved" },
    {   VID(304)    "Reserved" },
    {   VID(305)    "Reserved" },
    {   VID(306)    "Reserved" },
    {   VID(307)    "Hirose Electric Co., Ltd" },
    {   VID(308)    "Reserved" },
    {   VID(309)    "ProSoft Technology" },
    {   VID(310)    "Reserved" },
    {   VID(311)    "Reserved" },
    {   VID(312)    "Reserved" },
    {   VID(313)    "Reserved" },
    {   VID(314)    "Wieland Electric GmbH" },
    {   VID(315)    "SEW Eurodrive GmbH" },
    {   VID(316)    "Reserved" },
    {   VID(317)    "Reserved" },
    {   VID(318)    "Reserved" },
    {   VID(319)    "Fuji Electric Group" },
    {   VID(320)    "Reserved" },
    {   VID(321)    "Reserved" },
    {   VID(322)    "ifm electronic gmbh" },
    {   VID(323)    "Reserved" },
    {   VID(324)    "Reserved" },
    {   VID(325)    "Reserved" },
    {   VID(326)    "Intelligent Platforms, LLC." },
    {   VID(327)    "Reserved" },
    {   VID(328)    "Reserved" },
    {   VID(329)    "Reserved" },
    {   VID(330)    "Reserved" },
    {   VID(331)    "Interface Corporation" },
    {   VID(332)    "Reserved" },
    {   VID(333)    "Reserved" },
    {   VID(334)    "Reserved" },
    {   VID(335)    "Reserved" },
    {   VID(336)    "Reserved" },
    {   VID(337)    "Reserved" },
    {   VID(338)    "Reserved" },
    {   VID(339)    "Reserved" },
    {   VID(340)    "Alfa Laval LKM as" },
    {   VID(341)    "Reserved" },
    {   VID(342)    "Reserved" },
    {   VID(343)    "Reserved" },
    {   VID(344)    "KEBA Industrial Automation GmbH" },
    {   VID(346)    "Lincoln Electric Company" },
    {   VID(347)    "Reserved" },
    {   VID(348)    "Reserved" },
    {   VID(349)    "Reserved" },
    {   VID(350)    "Reserved" },
    {   VID(351)    "Reserved" },
    {   VID(352)    "Reserved" },
    {   VID(354)    "FRABA Posital" },
    {   VID(355)    "Reserved" },
    {   VID(356)    "FANUC Robotics America" },
    {   VID(357)    "Reserved" },
    {   VID(358)    "Reserved" },
    {   VID(359)    "Reserved" },
    {   VID(360)    "Reserved" },
    {   VID(361)    "Reserved" },
    {   VID(362)    "Reserved" },
    {   VID(363)    "Reserved" },
    {   VID(364)    "Reserved" },
    {   VID(365)    "Reserved" },
    {   VID(366)    "Reserved" },
    {   VID(367)    "Keyence Corporation" },
    {   VID(368)    "Reserved" },
    {   VID(369)    "Reserved" },
    {   VID(370)    "Reserved" },
    {   VID(371)    "Reserved" },
    {   VID(372)    "Reserved" },
    {   VID(373)    "Sumitomo Heavy Industries, Ltd." },
    {   VID(374)    "Reserved" },
    {   VID(375)    "Reserved" },
    {   VID(376)    "Reserved" },
    {   VID(377)    "TOSHIBA Schneider Inverter Corporation" },
    {   VID(378)    "Reserved" },
    {   VID(379)    "Reserved" },
    {   VID(380)    "Reserved" },
    {   VID(381)    "Reserved" },
    {   VID(382)    "Reserved" },
    {   VID(383)    "Reserved" },
    {   VID(384)    "Dyadic Systems Co., Ltd." },
    {   VID(385)    "Reserved" },
    {   VID(386)    "Reserved" },
    {   VID(387)    "Reserved" },
    {   VID(388)    "Reserved" },
    {   VID(389)    "Reserved" },
    {   VID(390)    "Reserved" },
    {   VID(391)    "Reserved" },
    {   VID(392)    "Reserved" },
    {   VID(393)    "Reserved" },
    {   VID(394)    "RKC Instrument Inc." },
    {   VID(395)    "Reserved" },
    {   VID(396)    "Reserved" },
    {   VID(397)    "Reserved" },
    {   VID(398)    "Selectron Systems AG" },
    {   VID(399)    "Reserved" },
    {   VID(400)    "LINTEC Co., Ltd." },
    {   VID(401)    "Reserved" },
    {   VID(402)    "Reserved" },
    {   VID(403)    "Reserved" },
    {   VID(404)    "VAT Vacuum Valves AG" },
    {   VID(405)    "Omron Robotics and Safety Technologies, Inc." },
    {   VID(406)    "Reserved" },
    {   VID(407)    "TWK Elektronik GmbH" },
    {   VID(408)    "Reserved" },
    {   VID(409)    "Reserved" },
    {   VID(410)    "Reserved" },
    {   VID(411)    "Reserved" },
    {   VID(412)    "Reserved" },
    {   VID(413)    "Kistler-Morse" },
    {   VID(414)    "Proteus Industries Inc." },
    {   VID(415)    "Reserved" },
    {   VID(416)    "Nordson Corporation" },
    {   VID(417)    "Reserved" },
    {   VID(418)    "Reserved" },
    {   VID(419)    "Reserved" },
    {   VID(420)    "Reserved" },
    {   VID(421)    "Reserved" },
    {   VID(422)    "Reserved" },
    {   VID(423)    "Bionics Instrument Co., Ltd." },
    {   VID(424)    "Teknic, Incorporated" },
    {   VID(426)    "Reserved" },
    {   VID(427)    "Reserved" },
    {   VID(428)    "Reserved" },
    {   VID(429)    "Koganei Corporation" },
    {   VID(430)    "Reserved" },
    {   VID(431)    "Nichigoh Communication Electric Wire Co., Ltd." },
    {   VID(433)    "Reserved" },
    {   VID(434)    "Reserved" },
    {   VID(435)    "Valmet Flow Control Inc (formerly StoneL)" },
    {   VID(436)    "Reserved" },
    {   VID(437)    "Reserved" },
    {   VID(438)    "Erhardt+Leimer GmbH" },
    {   VID(439)    "Reserved" },
    {   VID(440)    "Reserved" },
    {   VID(441)    "Nachi Fujikoshi Corporation" },
    {   VID(442)    "Reserved" },
    {   VID(443)    "Vacon Plc" },
    {   VID(444)    "Reserved" },
    {   VID(445)    "Reserved" },
    {   VID(446)    "Reserved" },
    {   VID(447)    "Reserved" },
    {   VID(448)    "Reserved" },
    {   VID(449)    "Reserved" },
    {   VID(450)    "Reserved" },
    {   VID(451)    "Reserved" },
    {   VID(452)    "Kollmorgen" },
    {   VID(453)    "Panasonic Smart Factory Solutions Co., Ltd." },
    {   VID(454)    "Reserved" },
    {   VID(455)    "Reserved" },
    {   VID(456)    "Reserved" },
    {   VID(457)    "Reserved" },
    {   VID(458)    "Reserved" },
    {   VID(459)    "Reserved" },
    {   VID(460)    "Reserved" },
    {   VID(461)    "Reserved" },
    {   VID(462)    "Reserved" },
    {   VID(463)    "Reserved" },
    {   VID(464)    "TRUMPF Huettinger" },
    {   VID(465)    "Reserved" },
    {   VID(466)    "Reserved" },
    {   VID(467)    "Reserved" },
    {   VID(468)    "Baumer IVO GmbH & Co. KG" },
    {   VID(469)    "Reserved" },
    {   VID(470)    "Reserved" },
    {   VID(471)    "Eilersen Electric A/S" },
    {   VID(472)    "Reserved" },
    {   VID(473)    "Reserved" },
    {   VID(474)    "Reserved" },
    {   VID(475)    "Reserved" },
    {   VID(476)    "Reserved" },
    {   VID(477)    "Reserved" },
    {   VID(478)    "Shimadzu Corporation" },
    {   VID(479)    "Reserved" },
    {   VID(480)    "Reserved" },
    {   VID(481)    "Reserved" },
    {   VID(482)    "Koyo Electronics Industries Co., Ltd." },
    {   VID(483)    "Reserved" },
    {   VID(484)    "Reserved" },
    {   VID(485)    "Reserved" },
    {   VID(486)    "Reserved" },
    {   VID(487)    "Reserved" },
    {   VID(488)    "Riken Keiki Co., Ltd." },
    {   VID(489)    "Reserved" },
    {   VID(490)    "Fuji Machine Mfg. Co., Ltd" },
    {   VID(491)    "Reserved" },
    {   VID(492)    "Reserved" },
    {   VID(493)    "Reserved" },
    {   VID(494)    "Reserved" },
    {   VID(495)    "Reserved" },
    {   VID(496)    "Reserved" },
    {   VID(497)    "Reserved" },
    {   VID(498)    "Reserved" },
    {   VID(499)    "Reserved" },
    {   VID(500)    "Reserved" },
    {   VID(501)    "YASKAWA Europe (formerly VIPA GmbH)" },
    {   VID(502)    "Reserved" },
    {   VID(503)    "Reserved" },
    {   VID(504)    "Reserved" },
    {   VID(505)    "Reserved" },
    {   VID(506)    "Reserved" },
    {   VID(507)    "Reserved" },
    {   VID(508)    "Reserved" },
    {   VID(509)    "Reserved" },
    {   VID(510)    "Proportion-Air, Inc." },
    {   VID(511)    "Reserved" },
    {   VID(512)    "Reserved" },
    {   VID(513)    "Reserved" },
    {   VID(514)    "Reserved" },
    {   VID(515)    "Cosmo Instruments Co., Ltd." },
    {   VID(516)    "Reserved" },
    {   VID(517)    "Reserved" },
    {   VID(518)    "Reserved" },
    {   VID(519)    "Reserved" },
    {   VID(520)    "Reserved" },
    {   VID(521)    "Fujikin, Inc." },
    {   VID(522)    "Reserved" },
    {   VID(523)    "Reserved" },
    {   VID(524)    "Leuze Electronic GmbH & Co. KG" },
    {   VID(525)    "Reserved" },
    {   VID(526)    "Reserved" },
    {   VID(527)    "Pfeiffer Vacuum GmbH" },
    {   VID(528)    "Reserved" },
    {   VID(529)    "OKUMA Corporation FA Systems Division" },
    {   VID(530)    "Reserved" },
    {   VID(531)    "Kokusai Electric Corporation" },
    {   VID(532)    "SHINKO TECHNOS" },
    {   VID(533)    "Itoh Denki Co., Ltd." },
    {   VID(534)    "Reserved" },
    {   VID(535)    "Reserved" },
    {   VID(536)    "Reserved" },
    {   VID(537)    "Reserved" },
    {   VID(538)    "Reserved" },
    {   VID(539)    "Reserved" },
    {   VID(540)    "Atlas Copco Airpower NV" },
    {   VID(541)    "Reserved" },
    {   VID(542)    "Reserved" },
    {   VID(543)    "Reserved" },
    {   VID(544)    "PMA GmbH" },
    {   VID(545)    "Reserved" },
    {   VID(546)    "Reserved" },
    {   VID(547)    "Reserved" },
    {   VID(548)    "JMACS" },
    {   VID(549)    "Reserved" },
    {   VID(550)    "Reserved" },
    {   VID(551)    "Reserved" },
    {   VID(552)    "Reserved" },
    {   VID(553)    "Reserved" },
    {   VID(554)    "Reserved" },
    {   VID(555)    "ATI Industrial Automation" },
    {   VID(556)    "Reserved" },
    {   VID(557)    "Reserved" },
    {   VID(558)    "Reserved" },
    {   VID(559)    "Reserved" },
    {   VID(560)    "Minebea Intec" },
    {   VID(561)    "Comau S.p.A. " },
    {   VID(562)    "Phoenix Contact" },
    {   VID(563)    "Reserved" },
    {   VID(564)    "Reserved" },
    {   VID(565)    "Valcom" },
    {   VID(566)    "Reserved" },
    {   VID(567)    "Reserved" },
    {   VID(568)    "Reserved" },
    {   VID(569)    "Reserved" },
    {   VID(570)    "Reserved" },
    {   VID(571)    "Reserved" },
    {   VID(572)    "ARO Welding Technologies S.A.S." },
    {   VID(573)    "Reserved" },
    {   VID(574)    "Reserved" },
    {   VID(575)    "Santest Co., Ltd." },
    {   VID(576)    "Reserved" },
    {   VID(577)    "Reserved" },
    {   VID(578)    "Reserved" },
    {   VID(579)    "Reserved" },
    {   VID(580)    "Reserved" },
    {   VID(581)    "Norgren Automation Solutions, LLC (previously Syron Engineering & Manufacturing, Inc.)" },
    {   VID(582)    "Reserved" },
    {   VID(583)    "Sansha Electric Mfg. Co.,Ltd." },
    {   VID(584)    "CKD Nikki Denso Co,. Ltd." },
    {   VID(585)    "Reserved" },
    {   VID(586)    "Reserved" },
    {   VID(587)    "Lenze" },
    {   VID(588)    "Reserved" },
    {   VID(589)    "LinMot" },
    {   VID(590)    "Delta Computer Systems, Inc." },
    {   VID(591)    "FANUC CORPORATION" },
    {   VID(592)    "Reserved" },
    {   VID(593)    "ABB Automation Products" },
    {   VID(594)    "Reserved" },
    {   VID(595)    "Reserved" },
    {   VID(596)    "Reserved" },
    {   VID(597)    "Reserved" },
    {   VID(598)    "Reserved" },
    {   VID(599)    "Toyogiken Co., Ltd." },
    {   VID(600)    "Reserved" },
    {   VID(601)    "Kawasaki Robot" },
    {   VID(602)    "Reserved" },
    {   VID(603)    "Robox S.p.a." },
    {   VID(604)    "Reserved" },
    {   VID(605)    "Benshaw Inc." },
    {   VID(606)    "Reserved" },
    {   VID(607)    "Reserved" },
    {   VID(608)    "Reserved" },
    {   VID(609)    "Reserved" },
    {   VID(610)    "Reserved" },
    {   VID(611)    "Reserved" },
    {   VID(612)    "Nor-Cal Products, Inc." },
    {   VID(613)    "Aros Electronics AB" },
    {   VID(614)    "Reserved" },
    {   VID(615)    "Reserved" },
    {   VID(616)    "Reserved" },
    {   VID(617)    "Reserved" },
    {   VID(618)    "Reserved" },
    {   VID(619)    "Reserved" },
    {   VID(620)    "Reserved" },
    {   VID(621)    "Reserved" },
    {   VID(622)    "Reserved" },
    {   VID(623)    "Reserved" },
    {   VID(624)    "Reserved" },
    {   VID(625)    "Rockwell Automation/Sprecher+Schuh" },
    {   VID(626)    "Panasonic Corporation/Motor Company" },
    {   VID(627)    "Reserved" },
    {   VID(628)    "Reserved" },
    {   VID(629)    "Interroll Engineering GmbH" },
    {   VID(630)    "Reserved" },
    {   VID(631)    "Reserved" },
    {   VID(632)    "Reserved" },
    {   VID(633)    "INFICON AG" },
    {   VID(634)    "Hirschmann, a Belden brand" },
    {   VID(635)    "The Siemon Company" },
    {   VID(636)    "YAMAHA Motor Co. Ltd." },
    {   VID(637)    "Reserved" },
    {   VID(638)    "Woodhead Connectivity" },
    {   VID(639)    "Reserved" },
    {   VID(640)    "Murrelektronik GmbH" },
    {   VID(641)    "Reserved" },
    {   VID(642)    "TopWorx" },
    {   VID(643)    "Reserved" },
    {   VID(644)    "Reserved" },
    {   VID(645)    "Bihl + Wiedemann GmbH" },
    {   VID(646)    "Reserved" },
    {   VID(647)    "Reserved" },
    {   VID(648)    "Reserved" },
    {   VID(649)    "Reserved" },
    {   VID(650)    "Reserved" },
    {   VID(651)    "Fife Corporation" },
    {   VID(652)    "Reserved" },
    {   VID(653)    "Detector Electronics" },
    {   VID(654)    "Reserved" },
    {   VID(655)    "Reserved" },
    {   VID(656)    "Reserved" },
    {   VID(657)    "Reserved" },
    {   VID(658)    "Reserved" },
    {   VID(659)    "Rotork Controls Ltd." },
    {   VID(660)    "Automationdirect.com" },
    {   VID(661)    "Reserved" },
    {   VID(662)    "Reserved" },
    {   VID(663)    "Univer S.p.A." },
    {   VID(664)    "Reserved" },
    {   VID(665)    "Lika Electronic" },
    {   VID(666)    "Mettler-Toledo" },
    {   VID(667)    "Reserved" },
    {   VID(668)    "Reserved" },
    {   VID(669)    "Reserved" },
    {   VID(670)    "Reserved" },
    {   VID(671)    "Reserved" },
    {   VID(672)    "Reserved" },
    {   VID(673)    "CONTEC CO., LTD." },
    {   VID(674)    "Reserved" },
    {   VID(675)    "Reserved" },
    {   VID(677)    "Reserved" },
    {   VID(678)    "Cognex Corporation" },
    {   VID(679)    "Reserved" },
    {   VID(680)    "Reserved" },
    {   VID(681)    "Reserved" },
    {   VID(682)    "Reserved" },
    {   VID(683)    "Wittenstein SE" },
    {   VID(684)    "Reserved" },
    {   VID(685)    "Reserved" },
    {   VID(686)    "SPX Flow Technology Germany GmbH" },
    {   VID(687)    "Reserved" },
    {   VID(688)    "Reserved" },
    {   VID(689)    "Reserved" },
    {   VID(690)    "Reserved" },
    {   VID(691)    "Littelfuse" },
    {   VID(692)    "Reserved" },
    {   VID(693)    "Reserved" },
    {   VID(694)    "Pfeiffer Vacuum SAS" },
    {   VID(695)    "Reserved" },
    {   VID(696)    "Reserved" },
    {   VID(697)    "Reserved" },
    {   VID(698)    "Reserved" },
    {   VID(699)    "IAI Corporation" },
    {   VID(700)    "Reserved" },
    {   VID(701)    "Reserved" },
    {   VID(702)    "Leine & Linde AB" },
    {   VID(703)    "Reserved" },
    {   VID(704)    "Reserved" },
    {   VID(705)    "Reserved" },
    {   VID(706)    "Bronkhorst High-Tech B.V." },
    {   VID(707)    "Reserved" },
    {   VID(708)    "Yosio Electronic Co." },
    {   VID(709)    "Reserved" },
    {   VID(710)    "Reserved" },
    {   VID(711)    "Reserved" },
    {   VID(712)    "Reserved" },
    {   VID(713)    "Reserved" },
    {   VID(714)    "Goyo Electronics Co, Ltd." },
    {   VID(715)    "Reserved" },
    {   VID(716)    "Reserved" },
    {   VID(717)    "Trumpf Laser GmbH + Co. KG" },
    {   VID(718)    "Reserved" },
    {   VID(719)    "Reserved" },
    {   VID(720)    "Reserved" },
    {   VID(721)    "Industrial Control Communication, Inc." },
    {   VID(723)    "Reserved" },
    {   VID(724)    "Reserved" },
    {   VID(725)    "Reserved" },
    {   VID(726)    "Reserved" },
    {   VID(727)    "Reserved" },
    {   VID(728)    "Yamato Scale Co., Ltd." },
    {   VID(729)    "Reserved" },
    {   VID(730)    "Reserved" },
    {   VID(731)    "Reserved" },
    {   VID(732)    "Beta LaserMike Limited" },
    {   VID(733)    "Reserved" },
    {   VID(734)    "Hakko Electronics Co., Ltd" },
    {   VID(735)    "Reserved" },
    {   VID(736)    "Reserved" },
    {   VID(737)    "Reserved" },
    {   VID(738)    "Reserved" },
    {   VID(739)    "Reserved" },
    {   VID(740)    "Camozzi Automation spa" },
    {   VID(741)    "Crevis Co., LTD" },
    {   VID(742)    "Rice Lake Weighing Systems" },
    {   VID(743)    "Reserved" },
    {   VID(744)    "KEB Automation KG" },
    {   VID(745)    "Reserved" },
    {   VID(746)    "Reserved" },
    {   VID(748)    "Reserved" },
    {   VID(749)    "Reserved" },
    {   VID(750)    "Reserved" },
    {   VID(751)    "Reserved" },
    {   VID(752)    "Reserved" },
    {   VID(753)    "Reserved" },
    {   VID(754)    "Reserved" },
    {   VID(755)    "Reserved" },
    {   VID(756)    "Reserved" },
    {   VID(757)    "Reserved" },
    {   VID(758)    "Reserved" },
    {   VID(759)    "Reserved" },
    {   VID(760)    "ABB Stotz Kontakt GmbH" },
    {   VID(761)    "Reserved" },
    {   VID(762)    "Reserved" },
    {   VID(763)    "Reserved" },
    {   VID(764)    "Reserved" },
    {   VID(765)    "Reserved" },
    {   VID(766)    "Reserved" },
    {   VID(767)    "Reserved" },
    {   VID(768)    "CSIRO Mining Automation" },
    {   VID(769)    "Reserved" },
    {   VID(770)    "Reserved" },
    {   VID(771)    "Reserved" },
    {   VID(772)    "Reserved" },
    {   VID(773)    "Reserved" },
    {   VID(774)    "Rocon L.L.C." },
    {   VID(775)    "Reserved" },
    {   VID(776)    "Reserved" },
    {   VID(777)    "Reserved" },
    {   VID(778)    "HARTING, Inc. of North America" },
    {   VID(779)    "Kuebler GmbH" },
    {   VID(780)    "Reserved" },
    {   VID(781)    "JEOL" },
    {   VID(782)    "Reserved" },
    {   VID(783)    "Reserved" },
    {   VID(784)    "Reserved" },
    {   VID(785)    "Reserved" },
    {   VID(786)    "Reserved" },
    {   VID(787)    "Reserved" },
    {   VID(788)    "Reserved" },
    {   VID(789)    "Reserved" },
    {   VID(790)    "Reserved" },
    {   VID(791)    "Reserved" },
    {   VID(792)    "Reserved" },
    {   VID(793)    "Metronix Messgerate u. Elektronik GmbH" },
    {   VID(794)    "ROPEX Industrie - Elektronik GmbH" },
    {   VID(795)    "Reserved" },
    {   VID(796)    "Siemens Industry, Inc." },
    {   VID(797)    "Reserved" },
    {   VID(798)    "TE Connectivity" },
    {   VID(799)    "Delta Electronics, Inc." },
    {   VID(800)    "Reserved" },
    {   VID(801)    "Autonics Corporation" },
    {   VID(802)    "Reserved" },
    {   VID(803)    "Reserved" },
    {   VID(804)    "Electro-Sensors, Inc." },
    {   VID(805)    "Reserved" },
    {   VID(806)    "Texas Instruments" },
    {   VID(807)    "Reserved" },
    {   VID(808)    "SICK AG" },
    {   VID(809)    "Reserved" },
    {   VID(810)    "Animatics Corporation" },
    {   VID(811)    "Reserved" },
    {   VID(812)    "Reserved" },
    {   VID(813)    "Reserved" },
    {   VID(814)    "Reserved" },
    {   VID(815)    "Reserved" },
    {   VID(816)    "Reserved" },
    {   VID(817)    "Reserved" },
    {   VID(818)    "Reserved" },
    {   VID(819)    "Reserved" },
    {   VID(820)    "Reserved" },
    {   VID(821)    "Reserved" },
    {   VID(822)    "Reserved" },
    {   VID(823)    "Reserved" },
    {   VID(824)    "Montalvo Corporation" },
    {   VID(825)    "Reserved" },
    {   VID(826)    "LEONI Special Cables GmbH" },
    {   VID(827)    "Reserved" },
    {   VID(828)    "Reserved" },
    {   VID(829)    "RS Automation Co., Ltd." },
    {   VID(830)    "Reserved" },
    {   VID(831)    "Reserved" },
    {   VID(832)    "Quest Technical Solutions, Inc." },
    {   VID(833)    "LS Cable" },
    {   VID(834)    "NORD Electronic DRIVESYSTEMS GmbH" },
    {   VID(835)    "Reserved" },
    {   VID(836)    "Reserved" },
    {   VID(837)    "Reserved" },
    {   VID(838)    "Reserved" },
    {   VID(839)    "Chugoku Electric Wire and Cable Co." },
    {   VID(840)    "Reserved" },
    {   VID(841)    "Panduit Corporation" },
    {   VID(842)    "Spellman High Voltage Electronics Corporation" },
    {   VID(843)    "Reserved" },
    {   VID(844)    "Reserved" },
    {   VID(845)    "ANYWIRE CORPORATION" },
    {   VID(846)    "Reserved" },
    {   VID(847)    "REO AG" },
    {   VID(848)    "Heraeus Noblelight Fusion UV Inc." },
    {   VID(849)    "Reserved" },
    {   VID(850)    "Datalogic, Inc." },
    {   VID(851)    "SoftPLC Corporation" },
    {   VID(852)    "Reserved" },
    {   VID(853)    "WEG" },
    {   VID(854)    "Teledyne LeCroy (formerly Frontline Test Equipment)" },
    {   VID(855)    "Reserved" },
    {   VID(856)    "Reserved" },
    {   VID(857)    "Reserved" },
    {   VID(858)    "Reserved" },
    {   VID(859)    "Reserved" },
    {   VID(860)    "Reserved" },
    {   VID(861)    "Reserved" },
    {   VID(862)    "Reserved" },
    {   VID(863)    "Reserved" },
    {   VID(864)    "NT International, an Entegris Company" },
    {   VID(865)    "Schweitzer Engineering Laboratories" },
    {   VID(866)    "Reserved" },
    {   VID(867)    "Reserved" },
    {   VID(868)    "Reserved" },
    {   VID(869)    "GEMUE GmbH & Co. KG" },
    {   VID(870)    "Reserved" },
    {   VID(871)    "Reserved" },
    {   VID(872)    "Reserved" },
    {   VID(873)    "Reserved" },
    {   VID(874)    "Reserved" },
    {   VID(875)    "MSA Safety" },
    {   VID(876)    "Reserved" },
    {   VID(877)    "Reserved" },
    {   VID(878)    "Reserved" },
    {   VID(879)    "PULS GmbH" },
    {   VID(880)    "Reserved" },
    {   VID(881)    "Reserved" },
    {   VID(882)    "Reserved" },
    {   VID(883)    "Automa SRL" },
    {   VID(884)    "Reserved" },
    {   VID(885)    "R. STAHL" },
    {   VID(886)    "Reserved" },
    {   VID(887)    "Bernecker + Rainer Industrie-Elektronik GmbH" },
    {   VID(888)    "Hiprom Technologies" },
    {   VID(889)    "Reserved" },
    {   VID(890)    "Reserved" },
    {   VID(891)    "Reserved" },
    {   VID(892)    "Reserved" },
    {   VID(893)    "Elcis Encoder s.r.l." },
    {   VID(894)    "Acromag, Inc." },
    {   VID(895)    "Avery Weigh-Tronix" },
    {   VID(896)    "Reserved" },
    {   VID(897)    "Reserved" },
    {   VID(899)    "Practicon Ltd." },
    {   VID(900)    "SCHUNK GmbH & Co. KG" },
    {   VID(901)    "Reserved" },
    {   VID(902)    "Reserved" },
    {   VID(903)    "Reserved" },
    {   VID(904)    "Reserved" },
    {   VID(905)    "Hottinger Baldwin Messtechnik GmbH" },
    {   VID(906)    "Teledyne DALSA" },
    {   VID(907)    "Reserved" },
    {   VID(908)    "Reserved" },
    {   VID(909)    "Pepperl+Fuchs Comtrol" },
    {   VID(910)    "Reserved" },
    {   VID(911)    "Regulateurs Europa Ltd" },
    {   VID(912)    "Reserved" },
    {   VID(913)    "Reserved" },
    {   VID(914)    "Micro Motion" },
    {   VID(915)    "Reserved" },
    {   VID(916)    "Reserved" },
    {   VID(917)    "CFT Ransburg Japan KK" },
    {   VID(918)    "Reserved" },
    {   VID(919)    "Reserved" },
    {   VID(920)    "NITTO SEIKO CO., LTD." },
    {   VID(921)    "Datalogic Machine Vision" },
    {   VID(922)    "Reserved" },
    {   VID(923)    "Reserved" },
    {   VID(924)    "Reserved" },
    {   VID(925)    "Reserved" },
    {   VID(926)    "Reserved" },
    {   VID(927)    "Misumi Corporation" },
    {   VID(928)    "GE Multilin" },
    {   VID(929)    "Reserved" },
    {   VID(930)    "Reserved" },
    {   VID(931)    "Reserved" },
    {   VID(932)    "Reserved" },
    {   VID(933)    "Reserved" },
    {   VID(934)    "Reserved" },
    {   VID(935)    "Aerotech Inc." },
    {   VID(936)    "JVL A/S" },
    {   VID(937)    "Reserved" },
    {   VID(938)    "Reserved" },
    {   VID(939)    "Cisco Systems, Inc." },
    {   VID(940)    "Grid Connect" },
    {   VID(941)    "Reserved" },
    {   VID(942)    "Reserved" },
    {   VID(943)    "Reserved" },
    {   VID(944)    "Taiyo Cable (Dongguan) Co., Ltd." },
    {   VID(945)    "Reserved" },
    {   VID(946)    "SEREN IPS INC" },
    {   VID(947)    "Belden" },
    {   VID(949)    "Gefran S.P.A." },
    {   VID(950)    "ABB (Jokab Safety)" },
    {   VID(951)    "Reserved" },
    {   VID(952)    "Biffi Italia srl" },
    {   VID(953)    "Reserved" },
    {   VID(954)    "Copley Controls " },
    {   VID(955)    "Reserved" },
    {   VID(956)    "Reserved" },
    {   VID(957)    "Frick Controls (div. of York International)" },
    {   VID(958)    "Reserved" },
    {   VID(959)    "Reserved" },
    {   VID(960)    "Kyosan Electric Mfg" },
    {   VID(961)    "Reserved" },
    {   VID(962)    "Reserved" },
    {   VID(963)    "Reserved" },
    {   VID(964)    "Reserved" },
    {   VID(965)    "NF Chiyoda Electronics Co., Ltd. " },
    {   VID(966)    "Flowserve Corporation" },
    {   VID(967)    "Reserved" },
    {   VID(968)    "IBA AG" },
    {   VID(969)    "Reserved" },
    {   VID(970)    "Reserved" },
    {   VID(971)    "Reserved" },
    {   VID(972)    "Eaton Automation GmbH (formerly Micro Innovation)" },
    {   VID(973)    "Reserved" },
    {   VID(974)    "Pre-Tech Co., Ltd." },
    {   VID(975)    "Reserved" },
    {   VID(976)    "Invensys Operations Management" },
    {   VID(977)    "Ametek HDR Power Systems" },
    {   VID(978)    "Reserved" },
    {   VID(979)    "TETRA-K Corporation" },
    {   VID(980)    "C&M Corporation" },
    {   VID(981)    "Siempelkamp Maschinen" },
    {   VID(982)    "Reserved" },
    {   VID(983)    "Daifuku Co., Ltd" },
    {   VID(984)    "Reserved" },
    {   VID(985)    "Reserved" },
    {   VID(986)    "Reserved" },
    {   VID(987)    "Reserved" },
    {   VID(988)    "Reserved" },
    {   VID(989)    "Reserved" },
    {   VID(990)    "Reserved" },
    {   VID(991)    "Moxa, Inc." },
    {   VID(992)    "Reserved" },
    {   VID(993)    "Reserved" },
    {   VID(994)    "Reserved" },
    {   VID(995)    "Reserved" },
    {   VID(996)    "Thorsis Technologies" },
    {   VID(997)    "Reserved" },
    {   VID(998)    "Reserved" },
    {   VID(999)    "Fairmount Automation, Inc." },
    {   VID(1000)   "Bird Electronic Corporation" },
    {   VID(1001)   "Reserved" },
    {   VID(1002)   "Reserved" },
    {   VID(1003)   "Reserved" },
    {   VID(1004)   "Reserved" },
    {   VID(1005)   "Reserved" },
    {   VID(1006)   "N-Tron Corporation, a Red Lion Company" },
    {   VID(1007)   "Reserved" },
    {   VID(1008)   "Reserved" },
    {   VID(1009)   "Seiko Epson Corporation" },
    {   VID(1010)   "halstrup-walcher GmbH" },
    {   VID(1011)   "Reserved" },
    {   VID(1012)   "Reserved" },
    {   VID(1013)   "Scolari Engineering S.p.A." },
    {   VID(1014)   "Reserved" },
    {   VID(1015)   "Weidmueller Group" },
    {   VID(1016)   "Reserved" },
    {   VID(1017)   "AEG Power Solutions GmbH" },
    {   VID(1018)   "Reserved" },
    {   VID(1019)   "Reserved" },
    {   VID(1020)   "Reserved" },
    {   VID(1021)   "J. Schmalz GmbH" },
    {   VID(1022)   "Reserved" },
    {   VID(1023)   "Reserved" },
    {   VID(1024)   "Reserved" },
    {   VID(1025)   "Reserved" },
    {   VID(1026)   "Reserved" },
    {   VID(1027)   "Reserved" },
    {   VID(1028)   "Reserved" },
    {   VID(1029)   "Reserved" },
    {   VID(1030)   "Reserved" },
    {   VID(1031)   "Reserved" },
    {   VID(1032)   "Reserved" },
    {   VID(1033)   "Reserved" },
    {   VID(1034)   "Reserved" },
    {   VID(1035)   "Reserved" },
    {   VID(1036)   "Reserved" },
    {   VID(1037)   "Reserved" },
    {   VID(1038)   "Reserved" },
    {   VID(1039)   "Reserved" },
    {   VID(1040)   "Cardinal Scale Mfg. Co." },
    {   VID(1041)   "METZ CONNECT USA Inc." },
    {   VID(1042)   "Reserved" },
    {   VID(1043)   "Reserved" },
    {   VID(1044)   "Reserved" },
    {   VID(1045)   "Reserved" },
    {   VID(1046)   "Reserved" },
    {   VID(1047)   "Reserved" },
    {   VID(1048)   "ORMEC Systems Corp." },
    {   VID(1049)   "Reserved" },
    {   VID(1050)   "Reserved" },
    {   VID(1051)   "Reserved" },
    {   VID(1052)   "Reserved" },
    {   VID(1053)   "Reserved" },
    {   VID(1054)   "Reserved" },
    {   VID(1055)   "Reserved" },
    {   VID(1056)   "Scancon A/S" },
    {   VID(1057)   "Reserved" },
    {   VID(1058)   "Reserved" },
    {   VID(1059)   "Reserved" },
    {   VID(1060)   "Innovasic" },
    {   VID(1061)   "Reserved" },
    {   VID(1062)   "Reserved" },
    {   VID(1063)   "Reserved" },
    {   VID(1064)   "Reserved" },
    {   VID(1065)   "Reserved" },
    {   VID(1066)   "ENDO KOGYO CO., LTD" },
    {   VID(1067)   "Reserved" },
    {   VID(1068)   "Reserved" },
    {   VID(1069)   "Reserved" },
    {   VID(1070)   "Joy Mining Machinery" },
    {   VID(1071)   "MPM Engineering Ltd." },
    {   VID(1072)   "Reserved" },
    {   VID(1073)   "Reserved" },
    {   VID(1074)   "Reserved" },
    {   VID(1075)   "Reserved" },
    {   VID(1076)   "Reserved" },
    {   VID(1077)   "Reserved" },
    {   VID(1078)   "Reserved" },
    {   VID(1079)   "Reserved" },
    {   VID(1080)   "Reserved" },
    {   VID(1081)   "Reserved" },
    {   VID(1082)   "Reserved" },
    {   VID(1083)   "Reserved" },
    {   VID(1084)   "Sciemetric Instruments Inc." },
    {   VID(1085)   "Reserved" },
    {   VID(1086)   "Mechatronics Co.,Ltd" },
    {   VID(1087)   "Reserved" },
    {   VID(1088)   "Reserved" },
    {   VID(1089)   "Reserved" },
    {   VID(1090)   "Acrison, Inc." },
    {   VID(1091)   "Applied Robotics, Inc." },
    {   VID(1092)   "FireBus LLC" },
    {   VID(1093)   "Sevenstar" },
    {   VID(1094)   "Reserved" },
    {   VID(1095)   "Omron Microscan Systems, Inc." },
    {   VID(1096)   "Reserved" },
    {   VID(1097)   "SensoPart Industriesensorik GmbH" },
    {   VID(1098)   "Tiefenbach Control Systems GmbH" },
    {   VID(1099)   "Reserved" },
    {   VID(1100)   "Reserved" },
    {   VID(1101)   "Reserved" },
    {   VID(1102)   "Reserved" },
    {   VID(1103)   "Reserved" },
    {   VID(1104)   "Power Electronics S.L." },
    {   VID(1105)   "Renesas Electronics" },
    {   VID(1106)   "Reserved" },
    {   VID(1107)   "Porter Engineering Ltd." },
    {   VID(1108)   "Reserved" },
    {   VID(1109)   "Inductive Automation" },
    {   VID(1110)   "Reserved" },
    {   VID(1111)   "Reserved" },
    {   VID(1112)   "Hitachi Industrial Equipment Systems Co.,Ltd." },
    {   VID(1113)   "Reserved" },
    {   VID(1114)   "port GmbH" },
    {   VID(1115)   "B & PLUS" },
    {   VID(1116)   "Graco Inc." },
    {   VID(1117)   "Reserved" },
    {   VID(1118)   "Reserved" },
    {   VID(1119)   "Reserved" },
    {   VID(1120)   "Reserved" },
    {   VID(1121)   "Reserved" },
    {   VID(1122)   "Reserved" },
    {   VID(1123)   "Reserved" },
    {   VID(1124)   "Fluke Networks" },
    {   VID(1125)   "Tetra Pak Packaging Solutions SpA" },
    {   VID(1126)   "Reserved" },
    {   VID(1127)   "Reserved" },
    {   VID(1128)   "Reserved" },
    {   VID(1129)   "Reserved" },
    {   VID(1130)   "Brother Industries, Ltd." },
    {   VID(1131)   "Reserved" },
    {   VID(1132)   "Leroy Automation" },
    {   VID(1133)   "Reserved" },
    {   VID(1134)   "THK Co., Ltd." },
    {   VID(1135)   "Reserved" },
    {   VID(1136)   "Reserved" },
    {   VID(1137)   "TR-Electronic GmbH" },
    {   VID(1138)   "Reserved" },
    {   VID(1139)   "Reserved" },
    {   VID(1140)   "Caterpillar Global Mining Europe GmbH" },
    {   VID(1141)   "Reserved" },
    {   VID(1142)   "Reserved" },
    {   VID(1143)   "Reserved" },
    {   VID(1144)   "Matrox Electronic Systems" },
    {   VID(1145)   "Reserved" },
    {   VID(1146)   "Reserved" },
    {   VID(1147)   "Reserved" },
    {   VID(1148)   "Reserved" },
    {   VID(1149)   "Reserved" },
    {   VID(1150)   "Promess Incorporated" },
    {   VID(1151)   "COPA-DATA GmbH" },
    {   VID(1152)   "Precision Engine Controls Corporation" },
    {   VID(1153)   "Reserved" },
    {   VID(1154)   "Lapp Group" },
    {   VID(1155)   "Reserved" },
    {   VID(1156)   "Reserved" },
    {   VID(1157)   "Aseptomag AG" },
    {   VID(1158)   "ARC Informatique" },
    {   VID(1159)   "Reserved" },
    {   VID(1160)   "Kobe Steel, Ltd." },
    {   VID(1161)   "FLIR Systems" },
    {   VID(1162)   "Xcelgo A/S" },
    {   VID(1163)   "STRATON AUTOMATION" },
    {   VID(1164)   "Reserved" },
    {   VID(1165)   "Swagelok" },
    {   VID(1166)   "Elspec" },
    {   VID(1167)   "Reserved" },
    {   VID(1168)   "Kunbus GmbH Industrial Communication" },
    {   VID(1169)   "Reserved" },
    {   VID(1170)   "Performance Controls, Inc." },
    {   VID(1171)   "ACS Motion Control, Ltd." },
    {   VID(1172)   "Reserved" },
    {   VID(1173)   "Reserved" },
    {   VID(1174)   "Alicat Scientific, Inc." },
    {   VID(1175)   "Reserved" },
    {   VID(1176)   "ADFweb.com SRL" },
    {   VID(1177)   "Reserved" },
    {   VID(1178)   "Reserved" },
    {   VID(1179)   "Vishay Nobel AB" },
    {   VID(1180)   "Reserved" },
    {   VID(1181)   "Emerson - SolaHD" },
    {   VID(1182)   "Endress+Hauser" },
    {   VID(1183)   "Bartec GmbH" },
    {   VID(1184)   "Reserved" },
    {   VID(1185)   "AccuSentry, Inc." },
    {   VID(1186)   "Curtiss Wright - Exlar Actuator Solutions" },
    {   VID(1187)   "Reserved" },
    {   VID(1188)   "Control Concepts, Inc." },
    {   VID(1189)   "Reserved" },
    {   VID(1190)   "Procon Engineering A Division of National Oilwell Varco UK Ltd" },
    {   VID(1191)   "Hermary" },
    {   VID(1192)   "Reserved" },
    {   VID(1193)   "Reserved" },
    {   VID(1194)   "Reserved" },
    {   VID(1195)   "Reserved" },
    {   VID(1196)   "Reserved" },
    {   VID(1197)   "Reserved" },
    {   VID(1198)   "Anton Paar GmbH" },
    {   VID(1199)   "Reserved" },
    {   VID(1200)   "Reserved" },
    {   VID(1201)   "Reserved" },
    {   VID(1202)   "Bonfiglioli Vectron GmbH" },
    {   VID(1203)   "Pivotal Systems" },
    {   VID(1204)   "Reserved" },
    {   VID(1205)   "Reserved" },
    {   VID(1206)   "Reserved" },
    {   VID(1207)   "Reserved" },
    {   VID(1208)   "Reserved" },
    {   VID(1209)   "Reserved" },
    {   VID(1210)   "Reserved" },
    {   VID(1211)   "wenglor sensoric gmbh" },
    {   VID(1212)   "Reserved" },
    {   VID(1213)   "MKP Co., Ltd." },
    {   VID(1214)   "Reserved" },
    {   VID(1215)   "Heinzmann GmbH & Co. KG" },
    {   VID(1216)   "Reserved" },
    {   VID(1217)   "Reserved" },
    {   VID(1218)   "Reserved" },
    {   VID(1219)   "FMS Force Measuring Systems AG" },
    {   VID(1220)   "Reserved" },
    {   VID(1221)   "Reserved" },
    {   VID(1222)   "Reserved" },
    {   VID(1223)   "Knorr-Bremse Espana, S.A. - Merak Division" },
    {   VID(1224)   "Reserved" },
    {   VID(1225)   "Reserved" },
    {   VID(1226)   "Reserved" },
    {   VID(1227)   "TMG Technologie und Engineering GmbH" },
    {   VID(1228)   "Reserved" },
    {   VID(1229)   "Reserved" },
    {   VID(1230)   "Tolomatic" },
    {   VID(1231)   "Dukane" },
    {   VID(1232)   "Reserved" },
    {   VID(1233)   "Jacobs Automation" },
    {   VID(1234)   "Reserved" },
    {   VID(1235)   "MSC Tuttlingen GmbH" },
    {   VID(1236)   "Reserved" },
    {   VID(1237)   "Reserved" },
    {   VID(1238)   "Reserved" },
    {   VID(1239)   "Reserved" },
    {   VID(1240)   "Penko Engineering B.V." },
    {   VID(1241)   "Z-Tec Automation Systems Inc." },
    {   VID(1242)   "ENTRON Controls LLC" },
    {   VID(1243)   "Johannes Huebner Fabrik Elektrischer Maschinen GmbH" },
    {   VID(1244)   "RF IDeas, Inc." },
    {   VID(1245)   "Pentronic AB" },
    {   VID(1246)   "Atlas Copco IAS GmbH" },
    {   VID(1247)   "TDK-Lambda" },
    {   VID(1248)   "Reserved" },
    {   VID(1249)   "Reserved" },
    {   VID(1250)   "Altronic LLC" },
    {   VID(1251)   "Siemens AG" },
    {   VID(1252)   "Liebherr Transportation Systems GmbH & Co KG" },
    {   VID(1253)   "Reserved" },
    {   VID(1254)   "Reserved" },
    {   VID(1255)   "Reserved" },
    {   VID(1256)   "LMI Technologies" },
    {   VID(1257)   "Reserved" },
    {   VID(1258)   "Reserved" },
    {   VID(1259)   "Reserved" },
    {   VID(1260)   "Reserved" },
    {   VID(1261)   "CEPHALOS Automatisierung mbH" },
    {   VID(1262)   "Reserved" },
    {   VID(1263)   "Reserved" },
    {   VID(1264)   "Reserved" },
    {   VID(1265)   "Quabbin Wire & Cable Co., Inc." },
    {   VID(1266)   "Reserved" },
    {   VID(1267)   "Reserved" },
    {   VID(1268)   "HORIBA Precision Instruments (Beijing) Co.,Ltd." },
    {   VID(1269)   "Reserved" },
    {   VID(1270)   "Rovema GmbH" },
    {   VID(1271)   "Reserved" },
    {   VID(1272)   "IEP GmbH" },
    {   VID(1273)   "Reserved" },
    {   VID(1274)   "Reserved" },
    {   VID(1275)   "Reserved" },
    {   VID(1276)   "Reserved" },
    {   VID(1277)   "Control Chief Corporation" },
    {   VID(1278)   "Reserved" },
    {   VID(1279)   "Reserved" },
    {   VID(1280)   "Reserved" },
    {   VID(1281)   "Reserved" },
    {   VID(1282)   "PRIMES GmbH" },
    {   VID(1283)   "Branson Ultrasonics" },
    {   VID(1284)   "DEIF A/S" },
    {   VID(1285)   "CODESYS GmbH" },
    {   VID(1286)   "Reserved" },
    {   VID(1287)   "Smarteye Corporation" },
    {   VID(1288)   "Shibaura Machine" },
    {   VID(1289)   "HMS/BU Ewon" },
    {   VID(1290)   "OFS" },
    {   VID(1291)   "KROHNE" },
    {   VID(1292)   "Reserved" },
    {   VID(1293)   "Reserved" },
    {   VID(1294)   "Reserved" },
    {   VID(1295)   "Kistler Instrumente AG" },
    {   VID(1296)   "Reserved" },
    {   VID(1297)   "Reserved" },
    {   VID(1298)   "Reserved" },
    {   VID(1299)   "Reserved" },
    {   VID(1300)   "Reserved" },
    {   VID(1301)   "Xylem Analytics Germany GmbH" },
    {   VID(1302)   "Lenord, Bauer & Co. GmbH" },
    {   VID(1303)   "Carlo Gavazzi Controls" },
    {   VID(1304)   "Faiveley Transport" },
    {   VID(1305)   "Reserved" },
    {   VID(1306)   "Sensia LLC" },
    {   VID(1307)   "Kepware Technologies" },
    {   VID(1308)   "duagon AG" },
    {   VID(1309)   "Reserved" },
    {   VID(1310)   "Xylem Water Solutions" },
    {   VID(1311)   "Automation Professionals, LLC" },
    {   VID(1312)   "Reserved" },
    {   VID(1313)   "CEIA SpA" },
    {   VID(1314)   "Reserved" },
    {   VID(1315)   "Alphagate Automatisierungstechnik GmbH" },
    {   VID(1316)   "Mecco Partners, LLC" },
    {   VID(1317)   "LAP GmbH Laser Applikationen" },
    {   VID(1318)   "ABB S.p.A. - SACE Division" },
    {   VID(1319)   "Reserved" },
    {   VID(1320)   "Reserved" },
    {   VID(1321)   "C.E. Electronics, Inc." },
    {   VID(1322)   "Thermo Ramsey Inc., a part of Thermo Fisher Scientific" },
    {   VID(1323)   "Helmholz GmbH & Co. KG" },
    {   VID(1324)   "EUCHNER GmbH + Co. KG" },
    {   VID(1325)   "AMKmotion" },
    {   VID(1326)   "Badger Meter" },
    {   VID(1327)   "Reserved" },
    {   VID(1328)   "Fisher-Rosemount Systems, Inc. doing business as Process Systems & Solutions" },
    {   VID(1329)   "LJU Automatisierungstechnik GmbH" },
    {   VID(1330)   "Fairbanks Scales, Inc." },
    {   VID(1331)   "Imperx, Inc." },
    {   VID(1332)   "FRONIUS International GmbH" },
    {   VID(1333)   "Hoffman Enclosures" },
    {   VID(1334)   "Elecsys Corporation" },
    {   VID(1335)   "Reserved" },
    {   VID(1336)   "RACO Manufacturing and Engineering" },
    {   VID(1337)   "Hein Lanz Industrial Tech." },
    {   VID(1338)   "Codenomicon" },
    {   VID(1339)   "SABO Elektronik GmbH" },
    {   VID(1340)   "Reserved" },
    {   VID(1341)   "Sensirion AG" },
    {   VID(1342)   "SIKO GmbH" },
    {   VID(1343)   "Reserved" },
    {   VID(1344)   "GRUNDFOS" },
    {   VID(1345)   "Reserved" },
    {   VID(1346)   "Beijer Electronics Products AB" },
    {   VID(1347)   "Reserved" },
    {   VID(1348)   "AIMCO" },
    {   VID(1349)   "Reserved" },
    {   VID(1350)   "Coval" },
    {   VID(1351)   "Powell Industries" },
    {   VID(1352)   "Reserved" },
    {   VID(1353)   "IPDisplays" },
    {   VID(1354)   "SCAIME SAS" },
    {   VID(1355)   "Metal Work SpA" },
    {   VID(1356)   "Telsonic AG" },
    {   VID(1357)   "Reserved" },
    {   VID(1358)   "Hauch & Bach ApS" },
    {   VID(1359)   "Pago AG" },
    {   VID(1360)   "ULTIMATE Europe Transportation Equipment GmbH" },
    {   VID(1361)   "Reserved" },
    {   VID(1362)   "FW Murphy Production Controls, LLC" },
    {   VID(1363)   "Lake Cable LLC" },
    {   VID(1364)   "Reserved" },
    {   VID(1365)   "Reserved" },
    {   VID(1366)   "Reserved" },
    {   VID(1367)   "Reserved" },
    {   VID(1368)   "Nanotec Electronic GmbH & Co. KG" },
    {   VID(1369)   "SAMWON ACT Co., Ltd." },
    {   VID(1370)   "Aparian Inc." },
    {   VID(1371)   "Cosys Inc." },
    {   VID(1372)   "Insight Automation Inc." },
    {   VID(1373)   "Reserved" },
    {   VID(1374)   "FASTECH" },
    {   VID(1375)   "K.A. Schmersal GmbH & Co. KG" },
    {   VID(1376)   "Reserved" },
    {   VID(1377)   "Reserved" },
    {   VID(1378)   "SEIDENSHA ELECTRONICS CO., LTD" },
    {   VID(1379)   "Reserved" },
    {   VID(1380)   "Don Electronics Ltd" },
    {   VID(1381)   "burster gmbh & co kg" },
    {   VID(1382)   "Unitronics (1989) (RG) LTD" },
    {   VID(1383)   "OEM Technology Solutions" },
    {   VID(1384)   "Allied Motion" },
    {   VID(1385)   "Reserved" },
    {   VID(1386)   "Dengensha TOA" },
    {   VID(1387)   "Systec Systemtechnik und Industrieautomation GmbH" },
    {   VID(1388)   "Reserved" },
    {   VID(1389)   "Jenny Science AG" },
    {   VID(1390)   "Baumer Optronic GmbH" },
    {   VID(1391)   "Invertek Drives Ltd" },
    {   VID(1392)   "High Grade Controls Corporation" },
    {   VID(1393)   "Reserved" },
    {   VID(1394)   "Reserved" },
    {   VID(1395)   "Reserved" },
    {   VID(1396)   "Actia Systems" },
    {   VID(1397)   "Reserved" },
    {   VID(1398)   "Beijing Tianma Intelligent Control Technology Co., Ltd" },
    {   VID(1399)   "Universal Robots A/S" },
    {   VID(1400)   "Reserved" },
    {   VID(1401)   "Dialight" },
    {   VID(1402)   "E-T-A Elektrotechnische Apparate GmbH" },
    {   VID(1403)   "Kemppi Oy" },
    {   VID(1404)   "Reserved" },
    {   VID(1405)   "ORing Industrial Networking Corp." },
    {   VID(1406)   "Reserved" },
    {   VID(1407)   "Reserved" },
    {   VID(1408)   "ELAP S.R.L." },
    {   VID(1409)   "Applied Mining Technologies" },
    {   VID(1410)   "KITZ SCT Corporation" },
    {   VID(1411)   "VTEX Corporation" },
    {   VID(1412)   "ESYSE GmbH Embedded Systems Engineering" },
    {   VID(1413)   "Automation Controls" },
    {   VID(1414)   "Reserved" },
    {   VID(1415)   "Cincinnati Test Systems" },
    {   VID(1416)   "Reserved" },
    {   VID(1417)   "Zumbach Electronics Corp." },
    {   VID(1418)   "Emerson Automation Solutions" },
    {   VID(1419)   "CCS Inc." },
    {   VID(1420)   "Videojet, Inc." },
    {   VID(1421)   "Zebra Technologies" },
    {   VID(1422)   "ANRITSU CORPORATION" },
    {   VID(1423)   "Dimetix AG" },
    {   VID(1424)   "General Measure (China)" },
    {   VID(1425)   "Fortress Interlocks" },
    {   VID(1426)   "Reserved" },
    {   VID(1427)   "Task Force Tips" },
    {   VID(1428)   "SERVO-ROBOT INC." },
    {   VID(1429)   "Flow Devices and Systems, Inc." },
    {   VID(1430)   "nLIGHT, Inc." },
    {   VID(1431)   "Microchip Technology Inc." },
    {   VID(1432)   "Reserved" },
    {   VID(1433)   "Reserved" },
    {   VID(1434)   "Accutron Instruments Inc." },
    {   VID(1435)   "Kaeser Kompressoren SE" },
    {   VID(1436)   "Reserved" },
    {   VID(1437)   "Coherix, Inc." },
    {   VID(1438)   "FLSmidth A/S" },
    {   VID(1439)   "Reserved" },
    {   VID(1440)   "Cole-Parmer Instrument Company" },
    {   VID(1441)   "Wachendorff Automation GmbH & Co., KG" },
    {   VID(1442)   "SMAC Moving Coil Actuators" },
    {   VID(1444)   "PushCorp, Inc." },
    {   VID(1445)   "Fluke Process Instruments GmbH" },
    {   VID(1446)   "Mini Motor S.p.a" },
    {   VID(1447)   "I-CON Industry Tech." },
    {   VID(1448)   "Grace Technologies" },
    {   VID(1449)   "Zaxis Inc." },
    {   VID(1450)   "Lumasense Technologies" },
    {   VID(1451)   "Domino Printing" },
    {   VID(1452)   "Reserved" },
    {   VID(1453)   "Reserved" },
    {   VID(1454)   "Altus Sistemas de Automação S.A." },
    {   VID(1455)   "Reserved" },
    {   VID(1456)   "InterTech Development Company" },
    {   VID(1457)   "Reserved" },
    {   VID(1458)   "Perle Systems Limited" },
    {   VID(1459)   "Utthunga Technologies Private Limited" },
    {   VID(1460)   "Reserved" },
    {   VID(1461)   "WIPOTEC GmbH" },
    {   VID(1462)   "Atos spa" },
    {   VID(1463)   "Solartron Metrology LTD" },
    {   VID(1464)   "Reserved" },
    {   VID(1465)   "Analog Devices" },
    {   VID(1466)   "Power Electronics International, Inc." },
    {   VID(1468)   "Campbell Wrapper Corporation" },
    {   VID(1469)   "Herkules-Resotec Elektronik GmbH" },
    {   VID(1470)   "aignep spa" },
    {   VID(1471)   "Reserved" },
    {   VID(1472)   "PMV Automation AB" },
    {   VID(1473)   "Reserved" },
    {   VID(1474)   "ProTec Dynatronix LLC dba Dynatronix" },
    {   VID(1475)   "Reserved" },
    {   VID(1476)   "Bitronics, LLC." },
    {   VID(1477)   "Delta Tau Data Systems" },
    {   VID(1478)   "Reserved" },
    {   VID(1479)   "Reserved" },
    {   VID(1480)   "ADB Safegate" },
    {   VID(1481)   "Reserved" },
    {   VID(1482)   "Reserved" },
    {   VID(1483)   "Artis GmbH" },
    {   VID(1484)   "REJ Co., LTD" },
    {   VID(1485)   "Vanderlande" },
    {   VID(1486)   "Packet Power" },
    {   VID(1487)   "ima-tec gmbh" },
    {   VID(1488)   "Vision Automation A/S" },
    {   VID(1489)   "PROCENTEC BV" },
    {   VID(1490)   "HETRONIK GmbH" },
    {   VID(1491)   "Lanmark Controls Inc." },
    {   VID(1492)   "Reserved" },
    {   VID(1493)   "flexlog GmbH" },
    {   VID(1494)   "YUCHANGTECH" },
    {   VID(1495)   "Dynapower Company" },
    {   VID(1496)   "TAKIKAWA ENGINEERING" },
    {   VID(1497)   "Ingersoll Rand" },
    {   VID(1498)   "ASA-RT s.r.l" },
    {   VID(1499)   "TRUMPF Schweiz AG" },
    {   VID(1500)   "Reserved" },
    {   VID(1501)   "Rinstrum    " },
    {   VID(1502)   "Reserved" },
    {   VID(1503)   "Reserved" },
    {   VID(1504)   "BlueBotics SA" },
    {   VID(1505)   "Dynapar Corporation" },
    {   VID(1506)   "Blum-Novotest" },
    {   VID(1507)   "CIMON" },
    {   VID(1508)   "Reserved" },
    {   VID(1509)   "Rethink Robotics GmbH" },
    {   VID(1510)   "Ingeteam Power Technology S. A." },
    {   VID(1511)   "TOSEI ENGINEERING CORP." },
    {   VID(1512)   "SAMSON AG" },
    {   VID(1513)   "TGW Mechanics GmbH" },
    {   VID(1514)   "Diatrend Corporation" },
    {   VID(1515)   "Reserved" },
    {   VID(1516)   "VAHLE Automation GmbH" },
    {   VID(1517)   "JSL Technology Co.,Ltd." },
    {   VID(1518)   "NetTechnix E&P GmbH" },
    {   VID(1519)   "Reserved" },
    {   VID(1520)   "Tecweigh" },
    {   VID(1521)   "IVEK Corporation" },
    {   VID(1522)   "Reserved" },
    {   VID(1523)   "AQ M-TECH AB " },
    {   VID(1524)   "Rexnord Industries LLC" },
    {   VID(1525)   "Reserved" },
    {   VID(1526)   "OPTEX FA Co., Ltd" },
    {   VID(1527)   "Volktek Corporation" },
    {   VID(1528)   "INGENIA" },
    {   VID(1529)   "Reserved" },
    {   VID(1530)   "Analytical Technology, Inc." },
    {   VID(1531)   "Columbus McKinnon Corporation " },
    {   VID(1532)   "HBC-radiomatic GmbH" },
    {   VID(1533)   "Leonton Technologies " },
    {   VID(1534)   "Mitsubishi Electric India Pvt. Ltd." },
    {   VID(1535)   "FOBA Laser, ALLTEC GmbH" },
    {   VID(1536)   "Leakmaster Inc" },
    {   VID(1537)   "Buhler AG" },
    {   VID(1538)   "LINAK Denmark A/S" },
    {   VID(1539)   "Reserved" },
    {   VID(1540)   "SIEB & MEYER AG" },
    {   VID(1541)   "Reserved" },
    {   VID(1542)   "Watson-Marlow Ltd" },
    {   VID(1543)   "ABB Switzerland Ltd - Low Voltage Products" },
    {   VID(1544)   "Reserved" },
    {   VID(1545)   "adphos" },
    {   VID(1546)   "Hangzhou Hikrobot Technology Co., Ltd." },
    {   VID(1547)   "TOSS GmbH & Co. KG" },
    {   VID(1548)   "Solar Turbines Incorporated" },
    {   VID(1549)   "Reserved" },
    {   VID(1550)   "Reserved" },
    {   VID(1551)   "Carlo Gavazzi Industri" },
    {   VID(1552)   "Nippon Gear" },
    {   VID(1553)   "OSIsoft, LLC" },
    {   VID(1554)   "Rinco Ultrasonics AG" },
    {   VID(1555)   "Reserved" },
    {   VID(1556)   "Reserved" },
    {   VID(1557)   "Mitutoyo" },
    {   VID(1558)   "swisca " },
    {   VID(1559)   "Micro-Epsilon Messtechnik GmbH & Co. KG" },
    {   VID(1560)   "AMADA MIYACHI AMERICA" },
    {   VID(1561)   "Taihan Electric Wire Co., Ltd." },
    {   VID(1562)   "JANOME Corporation" },
    {   VID(1563)   "ISHIDA " },
    {   VID(1564)   "NAKANISHI INC." },
    {   VID(1565)   "Mecademic Inc." },
    {   VID(1566)   "Reserved" },
    {   VID(1567)   "Sigma (NSW) PTY LTD" },
    {   VID(1568)   "Hammond Power Solutions Inc.-Mesta" },
    {   VID(1569)   "Reserved" },
    {   VID(1570)   "Reserved" },
    {   VID(1571)   "TRIDIMEO" },
    {   VID(1572)   "Motortronics UK Ltd." },
    {   VID(1573)   "Doosan Robotics" },
    {   VID(1574)   "ADVANCED Motion Controls" },
    {   VID(1575)   "OnRobot A/S" },
    {   VID(1576)   "Reserved" },
    {   VID(1577)   "Oetiker" },
    {   VID(1578)   "SICK OPTEX" },
    {   VID(1579)   "Reserved" },
    {   VID(1580)   "Reserved" },
    {   VID(1581)   "Kahler Automation Corporation" },
    {   VID(1582)   "Accuenergy (Canada) Inc." },
    {   VID(1583)   "TCI, LLC - An Allied Motion Company" },
    {   VID(1584)   "Sun Automation" },
    {   VID(1585)   "READY Robotics Corporation" },
    {   VID(1586)   "PEM, Power Eng & Mfg., Inc" },
    {   VID(1587)   "Dürr Somac GmbH" },
    {   VID(1588)   "Reserved" },
    {   VID(1589)   "Reserved" },
    {   VID(1590)   "Reserved" },
    {   VID(1591)   "RICOH Industrial Solutions Inc." },
    {   VID(1592)   "Shanghai Junqian Sensing Technology Co. Ltd." },
    {   VID(1593)   "Knick Elektronische Messgeräte GmbH & Co. KG" },
    {   VID(1594)   "Magnescale. Co., Ltd." },
    {   VID(1595)   "ICONICS, INC." },
    {   VID(1596)   "Weintek Labs., Inc" },
    {   VID(1597)   "Sherpa, Inc." },
    {   VID(1598)   "Inspekto A.M.V LTD" },
    {   VID(1599)   "Hydronix Ltd" },
    {   VID(1600)   "AIOI- SYSTEMS CO. LTD." },
    {   VID(1601)   "Ingenieurbüro Mewes & Partner GmbH" },
    {   VID(1602)   "HIGHYAG Lasertechnologie GmbH" },
    {   VID(1603)   "Ningbo Jetron Technology Co. Ltd." },
    {   VID(1604)   "Myostat Motion Control" },
    {   VID(1605)   "A-T Controls, Inc" },
    {   VID(1606)   "M2M craft Co., Ltd." },
    {   VID(1607)   "FUTEK Advanced Sensor Technology, Inc." },
    {   VID(1608)   "Cetek" },
    {   VID(1609)   "Norgren Manufacturing Co., Ltd." },
    {   VID(1610)   "Bernstein AG" },
    {   VID(1611)   "Hitachi Industrial Products, Ltd." },
    {   VID(1612)   "Reserved" },
    {   VID(1613)   "Duplomatic MS spa" },
    {   VID(1614)   "Ambrit Ltd" },
    {   VID(1615)   "Highlight Tech Corp." },
    {   VID(1616)   "New Power Plasma Co. Ltd." },
    {   VID(1617)   "AGCO Corporation" },
    {   VID(1618)   "Techman Robot" },
    {   VID(1619)   "Nabeya Bi-tech Kaisha" },
    {   VID(1620)   "Reserved" },
    {   VID(1621)   "Panasonic Corporation / Electric Works Company" },
    {   VID(1622)   "Cytiva" },
    {   VID(1623)   "Janasi Industries Ltd." },
    {   VID(1624)   "Haffmans BV" },
    {   VID(1625)   "Adaptek Systems" },
    {   VID(1626)   "Omniview Pty Ltd" },
    {   VID(1627)   "SVA Tech" },
    {   VID(1628)   "Dover Flexo Electronics" },
    {   VID(1629)   "Reserved" },
    {   VID(1630)   "IDEM Safety Switches" },
    {   VID(1631)   "Sonotroagel GmbH" },
    {   VID(1632)   "Thermo Gamma-Metrics LLC, a part of Thermo Fisher Scientific" },
    {   VID(1633)   "BBH Products" },
    {   VID(1634)   "RSI Elektrotechnik" },
    {   VID(1635)   "Carlo Gavazzi Ltd" },
    {   VID(1636)   "KOFLOC Corp." },
    {   VID(1637)   "VTScada by Trihedral" },
    {   VID(1638)   "Hach" },
    {   VID(1639)   "Cogniac " },
    {   VID(1640)   "Toshiba Infrastructure Systems & Solutions Corporation" },
    {   VID(1641)   "Cannon-Automata" },
    {   VID(1642)   "Rosenberger" },
    {   VID(1643)   "Blue-White Industries" },
    {   VID(1644)   "Cellumation GmbH" },
    {   VID(1645)   "TEAC Corp." },
    {   VID(1646)   "AEG Identifikationssysteme GmbH" },
    {   VID(1647)   "MARS TOHKEN SOLUTION CO.LTD." },
    {   VID(1648)   "Midas Technology Corp." },
    {   VID(1649)   "Dinkle Enterprise Co., Ltd." },
    {   VID(1650)   "THALES" },
    {   VID(1651)   "Dunkermotoren " },
    {   VID(1652)   "SONOTEC GmbH" },
    {   VID(1653)   "Brinkmann Pumpen" },
    {   VID(1654)   "Rheonics " },
    {   VID(1655)   "Precimeter" },
    {   VID(1656)   "Reserved" },
    {   VID(1657)   "ALGO SYSTEM CO., LTD." },
    {   VID(1658)   "Christ Electronic Systems GmbH" },
    {   VID(1659)   "JFcontrol Co., Ltd." },
    {   VID(1660)   "Shenzhen Inovance Technology Co., Ltd" },
    {   VID(1661)   "Rheonik Coriolis Mass Flow Sensors" },
    {   VID(1662)   "Ichor Systems, Inc." },
    {   VID(1663)   "di-soric GmbH & Co. KG" },
    {   VID(1664)   "Amphenol ICC" },
    {   VID(1665)   "Ningbo AirTAC Automation Industrial Co., Ltd. " },
    {   VID(1666)   "RSI" },
    {   VID(1667)   "Soft Robotics Inc." },
    {   VID(1668)   "MUSCLE CORPORATION" },
    {   VID(1669)   "Spotlight Systems LLC" },
    {   VID(1670)   "Afag Holding AG" },
    {   VID(1671)   "TELESIS TECHNOLOGIES INC" },
    {   VID(1672)   "SSI Schaefer Automation GmbH " },
    {   VID(1673)   "Super Systems, Inc." },
    {   VID(1674)   "CoreTigo LTD" },
    {   VID(1675)   "Inxpect SPA" },
    {   VID(1676)   "Kostal Industrie Elektrik GmbH" },
    {   VID(1677)   "JingQi（Tianjin）technology Co.,Ltd" },
    {   VID(1678)   "AGI Suretrack" },
    {   VID(1679)   "Shanghai JAKA Robotics Ltd" },
    {   VID(1680)   "Polarteknik Oy" },
    {   VID(1681)   "RoboteQ, Inc " },
    {   VID(1682)   "Uson" },
    {   VID(1683)   "Opt Machine Vision Tech Co., Ltd" },
    {   VID(1684)   "Asyril SA" },
    {   VID(1685)   "Georg Fischer Piping Systems" },
    {   VID(1686)   "Aber Instruments Ltd" },
    {   VID(1687)   "CodeWrights GmbH" },
    {   VID(1688)   "Neurala, Inc." },
    {   VID(1689)   "Panasonic Software Development Center Dalian Co.,Ltd." },
    {   VID(1690)   "Perinet GmbH" },
    {   VID(1691)   "MS Ultraschall Technologie GmbH" },
    {   VID(1692)   "PLASUS GmbH" },
    {   VID(1693)   "Nikon Corporation" },
    {   VID(1694)   "Shenzhen Hengzhiyuan Technology Corporation Ltd. " },
    {   VID(1695)   "Kowa Optronics Co., Ltd." },
    {   VID(1696)   "Specialist Mechanical Engineers" },
    {   VID(1697)   "CMD Corporation" },
    {   VID(1698)   "Sanwa Engineering Corp." },
    {   VID(1699)   "Intellore Systems Pvt. Ltd" },
    {   VID(1700)   "Toledo e Souza" },
    {   VID(1701)   "PBS Biotech, Inc" },
    {   VID(1702)   "PLANET Technology Corporation" },
    {   VID(1703)   "Robatech AG" },
    {   VID(1704)   "MARKEM-IMAJE" },
    {   VID(1705)   "Novanta IMS" },
    {   VID(1706)   "Bamboo-Dynamics" },
    {   VID(1707)   "FACTS Engineering, LLC" },
    {   VID(1708)   "Digital Dynamics" },
    {   VID(1709)   "Fatek Automation Corporation" },
    {   VID(1710)   "Hanwha " },
    {   VID(1711)   "Fukuda" },
    {   VID(1712)   "Zhejiang Eternal Automation Sci-Tec Co.,Ltd" },
    {   VID(1713)   "KYOWA ELECTRONIC INSTRUMENTS CO.,LTD." },
    {   VID(1714)   "Vaisala Oyj" },
    {   VID(1715)   "Hennecke GmbH" },
    {   VID(1716)   "Encoder Products Company" },
    {   VID(1717)   "Converting Equipment International (dba CEI)" },
    {   VID(1718)   "Reserved" },
    {   VID(1719)   "Kinova " },
    {   VID(1720)   "The Poling Group, Inc." },
    {   VID(9876)   "ODVA" },
    {   VID(9999)   "Reserved" },
    {   VID(9999)   "Reserved" },
    {   VID(9999)   "Reserved" },
};


#define HAVE_BSEARCH    1

#define VENDOR_COUNT     int( sizeof(vendors)/sizeof(vendors[0]))


#if defined(HAVE_BSEARCH)

#include <stdlib.h>         // bsearch()

static int compare( const void* a1, const void* a2 )
{
    const VendorRow* v1 = (const VendorRow*) a1;
    const VendorRow* v2 = (const VendorRow*) a2;

    int ret = v1->id - v2->id;
    return ret;
}


const char* CipVendorStr( int aVendorId )
{
    static char buf[16];

    VendorRow search;

    search.id = aVendorId;

    const VendorRow* findings = (const VendorRow*) bsearch(
            &search,
            vendors, VENDOR_COUNT,
            sizeof(VendorRow), compare );

    if( findings )
        return findings->name;
    else
    {
        snprintf( buf, sizeof(buf), "%d", aVendorId );
        return buf;
    }
}


#else

const char* CipVendorStr( int aVendorId )
{
    static char buf[16];

    for( int i = 0; i < VENDOR_COUNT;  ++i )
    {
        if( vendors[i].id == aVendorId )
            return vendors[i].name;
    }

    snprintf( buf, sizeof(buf), "%d", aVendorId );

    return buf;
}

#endif


#if 0

#include <stdlib.h>

int main( int argc, char** argv )
{
#if 0
    for( int i =0; i < VENDOR_COUNT;  ++i )
    {
        if( vendors[i].id != i )
        {
            printf( "vendors[%d].id==%d\n", i, vendors[i].id );
        }
    }
#endif

    if( argc != 2 )
    {
        fprintf( stderr, "Usage: %s <vendor_id>\n", argv[0] );
        exit( 1 );
    }


    int id = strtoul( argv[1], NULL, 0 );

    printf( "id:%d  name:'%s'\n",  id, CipVendorStr( id ) );
}

#endif

