
#include <stdio.h>
#include "cipcommon.h"

//#define VID(x)      // nothing
#define VID(x)      x,

/* Translate Vendor IDs */
static const struct VendorRow {
    short       id;
    const char* name;
} vendors[] = {
    {   VID(0)      "Reserved" },
    {   VID(1)      "Rockwell Automation/Allen-Bradley" },
    {   VID(2)      "Namco Controls Corp." },
    {   VID(3)      "Honeywell Inc." },
    {   VID(4)      "Parker Hannifin Corp. (Veriflo Division)" },
    {   VID(5)      "Rockwell Automation/Reliance Elec." },
    {   VID(6)      "Reserved" },
    {   VID(7)      "SMC Corporation" },
    {   VID(8)      "Molex Incorporated" },
    {   VID(9)      "Western Reserve Controls Corp." },
    {   VID(10)     "Advanced Micro Controls Inc. (AMCI)" },
    {   VID(11)     "ASCO Pneumatic Controls" },
    {   VID(12)     "Banner Engineering Corp." },
    {   VID(13)     "Belden Wire & Cable Company" },
    {   VID(14)     "Cooper Interconnect" },
    {   VID(15)     "Reserved" },
    {   VID(16)     "Daniel Woodhead Co. (Woodhead Connectivity)" },
    {   VID(17)     "Dearborn Group Inc." },
    {   VID(18)     "Reserved" },
    {   VID(19)     "Helm Instrument Company" },
    {   VID(20)     "Huron Net Works" },
    {   VID(21)     "Lumberg, Inc." },
    {   VID(22)     "Online Development Inc.(Automation Value)" },
    {   VID(23)     "Vorne Industries, Inc." },
    {   VID(24)     "ODVA Special Reserve" },
    {   VID(25)     "Reserved" },
    {   VID(26)     "Festo Corporation" },
    {   VID(27)     "Reserved" },
    {   VID(28)     "Reserved" },
    {   VID(29)     "Reserved" },
    {   VID(30)     "Unico, Inc." },
    {   VID(31)     "Ross Controls" },
    {   VID(32)     "Reserved" },
    {   VID(33)     "Reserved" },
    {   VID(34)     "Hohner Corp." },
    {   VID(35)     "Micro Mo Electronics, Inc." },
    {   VID(36)     "MKS Instruments, Inc." },
    {   VID(37)     "Yaskawa Electric America formerly Magnetek Drives" },
    {   VID(38)     "Reserved" },
    {   VID(39)     "AVG Automation (Uticor)" },
    {   VID(40)     "Wago Corporation" },
    {   VID(41)     "Kinetics (Unit Instruments)" },
    {   VID(42)     "IMI Norgren Limited" },
    {   VID(43)     "BALLUFF, Inc." },
    {   VID(44)     "Yaskawa Electric America, Inc." },
    {   VID(45)     "Eurotherm Controls Inc" },
    {   VID(46)     "ABB Industrial Systems" },
    {   VID(47)     "Omron Corporation" },
    {   VID(48)     "TURCk, Inc." },
    {   VID(49)     "Grayhill Inc." },
    {   VID(50)     "Real Time Automation (C&ID)" },
    {   VID(51)     "Reserved" },
    {   VID(52)     "Numatics, Inc." },
    {   VID(53)     "Lutze, Inc." },
    {   VID(54)     "Reserved" },
    {   VID(55)     "Reserved" },
    {   VID(56)     "Softing GmbH" },
    {   VID(57)     "Pepperl + Fuchs" },
    {   VID(58)     "Spectrum Controls, Inc." },
    {   VID(59)     "D.I.P. Inc. MKS Inst." },
    {   VID(60)     "Applied Motion Products, Inc." },
    {   VID(61)     "Sencon Inc." },
    {   VID(62)     "High Country Tek" },
    {   VID(63)     "SWAC Automation Consult GmbH" },
    {   VID(64)     "Clippard Instrument Laboratory" },
    {   VID(65)     "Reserved" },
    {   VID(66)     "Reserved" },
    {   VID(67)     "Reserved" },
    {   VID(68)     "Eaton Electrical" },
    {   VID(69)     "Reserved" },
    {   VID(70)     "Reserved" },
    {   VID(71)     "Toshiba International Corp." },
    {   VID(72)     "Control Technology Incorporated" },
    {   VID(73)     "TCS (NZ) Ltd." },
    {   VID(74)     "Hitachi, Ltd." },
    {   VID(75)     "ABB Robotics Products AB" },
    {   VID(76)     "NKE Corporation" },
    {   VID(77)     "Rockwell Software, Inc." },
    {   VID(78)     "Escort Memory Systems (A Datalogic Group Co.)" },
    {   VID(79)     "Reserved" },
    {   VID(80)     "Industrial Devices Corporation" },
    {   VID(81)     "IXXAT Automation GmbH" },
    {   VID(82)     "Mitsubishi Electric Automation, Inc." },
    {   VID(83)     "OPTO-22" },
    {   VID(84)     "Reserved" },
    {   VID(85)     "Reserved" },
    {   VID(86)     "Horner Electric" },
    {   VID(87)     "Burkert Werke GmbH & Co. KG" },
    {   VID(88)     "Reserved" },
    {   VID(89)     "Industrial Indexing Systems, Inc." },
    {   VID(90)     "HMS Industrial Networks AB" },
    {   VID(91)     "Robicon" },
    {   VID(92)     "Helix Technology (Granville-Phillips)" },
    {   VID(93)     "Arlington Laboratory" },
    {   VID(94)     "Advantech Co. Ltd." },
    {   VID(95)     "Square D Company" },
    {   VID(96)     "Digital Electronics Corp." },
    {   VID(97)     "Danfoss" },
    {   VID(98)     "Reserved" },
    {   VID(99)     "Reserved" },
    {   VID(100)    "Bosch Rexroth Corporation, Pneumatics" },
    {   VID(101)    "Applied Materials, Inc." },
    {   VID(102)    "Showa Electric Wire & Cable Co." },
    {   VID(103)    "Pacific Scientific (API Controls Inc.)" },
    {   VID(104)    "Sharp Manufacturing Systems Corp." },
    {   VID(105)    "Olflex Wire & Cable, Inc." },
    {   VID(106)    "Reserved" },
    {   VID(107)    "Unitrode" },
    {   VID(108)    "Beckhoff Automation GmbH" },
    {   VID(109)    "National Instruments" },
    {   VID(110)    "Mykrolis Corporations (Millipore)" },
    {   VID(111)    "International Motion Controls Corp." },
    {   VID(112)    "Reserved" },
    {   VID(113)    "SEG Kempen GmbH" },
    {   VID(114)    "Reserved" },
    {   VID(115)    "Reserved" },
    {   VID(116)    "MTS Systems Corp." },
    {   VID(117)    "Krones, Inc" },
    {   VID(118)    "Reserved" },
    {   VID(119)    "EXOR Electronic R & D" },
    {   VID(120)    "SIEI S.p.A." },
    {   VID(121)    "KUKA Roboter GmbH" },
    {   VID(122)    "Reserved" },
    {   VID(123)    "SEC (Samsung Electronics Co., Ltd)" },
    {   VID(124)    "Binary Electronics Ltd" },
    {   VID(125)    "Flexible Machine Controls" },
    {   VID(126)    "Reserved" },
    {   VID(127)    "ABB Inc. (Entrelec)" },
    {   VID(128)    "MAC Valves, Inc." },
    {   VID(129)    "Auma Actuators Inc" },
    {   VID(130)    "Toyoda Machine Works, Ltd" },
    {   VID(131)    "Reserved" },
    {   VID(132)    "Reserved" },
    {   VID(133)    "Balogh T.A.G., Corporation" },
    {   VID(134)    "TR Systemtechnik GmbH" },
    {   VID(135)    "UNIPULSE Corporation" },
    {   VID(136)    "Reserved" },
    {   VID(137)    "Reserved" },
    {   VID(138)    "Conxall Corporation Inc." },
    {   VID(139)    "Reserved" },
    {   VID(140)    "Reserved" },
    {   VID(141)    "Kuramo Electric Co., Ltd." },
    {   VID(142)    "Creative Micro Designs" },
    {   VID(143)    "GE Industrial Systems" },
    {   VID(144)    "Leybold Vacuum GmbH" },
    {   VID(145)    "Siemens Energy & Automation/Drives" },
    {   VID(146)    "Kodensha Ltd" },
    {   VID(147)    "Motion Engineering, Inc." },
    {   VID(148)    "Honda Engineering Co., Ltd" },
    {   VID(149)    "EIM Valve Controls" },
    {   VID(150)    "Melec Inc." },
    {   VID(151)    "Sony Manufacturing Systems Corporation" },
    {   VID(152)    "North American Mfg." },
    {   VID(153)    "WATLOW" },
    {   VID(154)    "Japan Radio Co., Ltd" },
    {   VID(155)    "NADEX Co., Ltd" },
    {   VID(156)    "Ametek Automation & Process Technologies" },
    {   VID(157)    "Reserved" },
    {   VID(158)    "KVASER AB" },
    {   VID(159)    "IDEC IZUMI Corporation" },
    {   VID(160)    "Mitsubishi Heavy Industries Ltd" },
    {   VID(161)    "Mitsubishi Electric Corporation" },
    {   VID(162)    "Horiba-STEC Inc." },
    {   VID(163)    "esd electronic system design gmbh" },
    {   VID(164)    "DAIHEN Corporation" },
    {   VID(165)    "Tyco Valves & Controls/Keystone" },
    {   VID(166)    "EBARA Corporation" },
    {   VID(167)    "Reserved" },
    {   VID(168)    "Reserved" },
    {   VID(169)    "Hokuyo Electric Co. Ltd" },
    {   VID(170)    "Pyramid Solutions, Inc." },
    {   VID(171)    "Denso Wave Incorporated" },
    {   VID(172)    "HLS Hard-Line Solutions Inc" },
    {   VID(173)    "Caterpillar, Inc." },
    {   VID(174)    "PDL Electronics Ltd." },
    {   VID(175)    "Reserved" },
    {   VID(176)    "Red Lion Controls" },
    {   VID(177)    "ANELVA Corporation" },
    {   VID(178)    "Toyo Denki Seizo KK" },
    {   VID(179)    "Sanyo Denki Co., Ltd" },
    {   VID(180)    "Advanced Energy Japan K.K. (Aera Japan)" },
    {   VID(181)    "Pilz GmbH & Co" },
    {   VID(182)    "Marsh Bellofram-Bellofram PCD Division" },
    {   VID(183)    "Reserved" },
    {   VID(184)    "M-SYSTEM Co. Ltd" },
    {   VID(185)    "Nissin Electric Co., Ltd" },
    {   VID(186)    "Hitachi Metals Ltd." },
    {   VID(187)    "Oriental Motor Company" },
    {   VID(188)    "A&D Co., Ltd" },
    {   VID(189)    "Phasetronics, Inc." },
    {   VID(190)    "Cummins Engine Company" },
    {   VID(191)    "Deltron Inc." },
    {   VID(192)    "Geneer Corporation" },
    {   VID(193)    "Anatol Automation, Inc." },
    {   VID(194)    "Reserved" },
    {   VID(195)    "Reserved" },
    {   VID(196)    "Medar, Inc." },
    {   VID(197)    "Comdel Inc." },
    {   VID(198)    "Advanced Energy Industries, Inc" },
    {   VID(199)    "Reserved" },
    {   VID(200)    "DAIDEN Co., Ltd" },
    {   VID(201)    "CKD Corporation" },
    {   VID(202)    "Toyo Electric Corporation" },
    {   VID(203)    "Reserved" },
    {   VID(204)    "AuCom Electronics Ltd" },
    {   VID(205)    "Shinko Electric Co., Ltd" },
    {   VID(206)    "Vector Informatik GmbH" },
    {   VID(207)    "Reserved" },
    {   VID(208)    "Moog Inc." },
    {   VID(209)    "Contemporary Controls" },
    {   VID(210)    "Tokyo Sokki Kenkyujo Co., Ltd" },
    {   VID(211)    "Schenck-AccuRate, Inc." },
    {   VID(212)    "The Oilgear Company" },
    {   VID(213)    "Reserved" },
    {   VID(214)    "ASM Japan K.K." },
    {   VID(215)    "HIRATA Corp." },
    {   VID(216)    "SUNX Limited" },
    {   VID(217)    "Meidensha Corp." },
    {   VID(218)    "NIDEC SANKYO CORPORATION (Sankyo Seiki Mfg. Co., Ltd)" },
    {   VID(219)    "KAMRO Corp." },
    {   VID(220)    "Nippon System Development Co., Ltd" },
    {   VID(221)    "EBARA Technologies Inc." },
    {   VID(222)    "Reserved" },
    {   VID(223)    "Reserved" },
    {   VID(224)    "SG Co., Ltd" },
    {   VID(225)    "Vaasa Institute of Technology" },
    {   VID(226)    "MKS Instruments (ENI Technology)" },
    {   VID(227)    "Tateyama System Laboratory Co., Ltd." },
    {   VID(228)    "QLOG Corporation" },
    {   VID(229)    "Matric Limited Inc." },
    {   VID(230)    "NSD Corporation" },
    {   VID(231)    "Reserved" },
    {   VID(232)    "Sumitomo Wiring Systems, Ltd" },
    {   VID(233)    "Group 3 Technology Ltd" },
    {   VID(234)    "CTI Cryogenics" },
    {   VID(235)    "POLSYS CORP" },
    {   VID(236)    "Ampere Inc." },
    {   VID(237)    "Reserved" },
    {   VID(238)    "Simplatroll Ltd" },
    {   VID(239)    "Reserved" },
    {   VID(240)    "Reserved" },
    {   VID(241)    "Leading Edge Design" },
    {   VID(242)    "Humphrey Products" },
    {   VID(243)    "Schneider Automation, Inc." },
    {   VID(244)    "Westlock Controls Corp." },
    {   VID(245)    "Nihon Weidmuller Co., Ltd" },
    {   VID(246)    "Brooks Instrument (Div. of Emerson)" },
    {   VID(247)    "Reserved" },
    {   VID(248)    " Moeller GmbH" },
    {   VID(249)    "Varian Vacuum Products" },
    {   VID(250)    "Yokogawa Electric Corporation" },
    {   VID(251)    "Electrical Design Daiyu Co., Ltd" },
    {   VID(252)    "Omron Software Co., Ltd" },
    {   VID(253)    "BOC Edwards" },
    {   VID(254)    "Control Technology Corporation" },
    {   VID(255)    "Bosch Rexroth" },
    {   VID(256)    "Turck" },
    {   VID(257)    "Control Techniques PLC" },
    {   VID(258)    "Hardy Instruments, Inc." },
    {   VID(259)    "LS Industrial Systems" },
    {   VID(260)    "E.O.A. Systems Inc." },
    {   VID(261)    "Reserved" },
    {   VID(262)    "New Cosmos Electric Co., Ltd." },
    {   VID(263)    "Sense Eletronica LTDA" },
    {   VID(264)    "Xycom, Inc." },
    {   VID(265)    "Baldor Electric" },
    {   VID(266)    "Reserved" },
    {   VID(267)    "Patlite Corporation" },
    {   VID(268)    "Reserved" },
    {   VID(269)    "Mogami Wire & Cable Corporation" },
    {   VID(270)    "Welding Technology Corporation (WTC)" },
    {   VID(271)    "Reserved" },
    {   VID(272)    "Deutschmann Automation GmbH" },
    {   VID(273)    "ICP Panel-Tec Inc." },
    {   VID(274)    "Bray Controls USA" },
    {   VID(275)    "Reserved" },
    {   VID(276)    "Status Technologies" },
    {   VID(277)    "Trio Motion Technology Ltd" },
    {   VID(278)    "Sherrex Systems Ltd" },
    {   VID(279)    "Adept Technology, Inc." },
    {   VID(280)    "Spang Power Electronics" },
    {   VID(281)    "Reserved" },
    {   VID(282)    "Acrosser Technology Co., Ltd" },
    {   VID(283)    "Hilscher GmbH" },
    {   VID(284)    "IMAX Corporation" },
    {   VID(285)    "Electronic Innovation, Inc. (Falter Engineering)" },
    {   VID(286)    "Netlogic Inc." },
    {   VID(287)    "Bosch Rexroth Corporation, Indramat" },
    {   VID(288)    "Reserved" },
    {   VID(289)    "Reserved" },
    {   VID(290)    "Murata  Machinery Ltd." },
    {   VID(291)    "MTT Company Ltd." },
    {   VID(292)    "Kanematsu Semiconductor Corp." },
    {   VID(293)    "Takebishi Electric Sales Co." },
    {   VID(294)    "Tokyo Electron Device Ltd" },
    {   VID(295)    "PFU Limited" },
    {   VID(296)    "Hakko Automation Co., Ltd." },
    {   VID(297)    "Advanet Inc." },
    {   VID(298)    "Tokyo Electron Software Technologies Ltd." },
    {   VID(299)    "Reserved" },
    {   VID(300)    "Shinagawa Electric Wire Co., Ltd." },
    {   VID(301)    "Yokogawa M&C Corporation" },
    {   VID(302)    "KONAN Electric Co., Ltd." },
    {   VID(303)    "Binar Elektronik AB" },
    {   VID(304)    "Furukawa Electric Co." },
    {   VID(305)    "Cooper Energy Services" },
    {   VID(306)    "Schleicher GmbH & Co." },
    {   VID(307)    "Hirose Electric Co., Ltd" },
    {   VID(308)    "Western Servo Design Inc." },
    {   VID(309)    "Prosoft Technology" },
    {   VID(310)    "Reserved" },
    {   VID(311)    "Towa Shoko Co., Ltd" },
    {   VID(312)    "Kyopal Co., Ltd" },
    {   VID(313)    "Extron Co." },
    {   VID(314)    "Wieland Electric GmbH" },
    {   VID(315)    "SEW Eurodrive GmbH" },
    {   VID(316)    "Aera Corporation" },
    {   VID(317)    "STA Reutlingen" },
    {   VID(318)    "Reserved" },
    {   VID(319)    "Fuji Electric Co., Ltd." },
    {   VID(320)    "Reserved" },
    {   VID(321)    "Reserved" },
    {   VID(322)    "ifm efector, inc." },
    {   VID(323)    "Reserved" },
    {   VID(324)    "IDEACOD-Hohner Automation S.A." },
    {   VID(325)    "CommScope Inc." },
    {   VID(326)    "GE Fanuc Automation North America, Inc." },
    {   VID(327)    "Matsushita Electric Industrial Co., Ltd" },
    {   VID(328)    "Okaya Electronics Corporation" },
    {   VID(329)    "KASHIYAMA Industries, Ltd" },
    {   VID(330)    "JVC" },
    {   VID(331)    "Interface Corporation" },
    {   VID(332)    "Grape Systems Inc." },
    {   VID(333)    "Reserved" },
    {   VID(334)    "Reserved" },
    {   VID(335)    "Toshiba IT & Control Systems Corporation" },
    {   VID(336)    "Sanyo Machine Works, Ltd." },
    {   VID(337)    "Vansco Electronics Ltd." },
    {   VID(338)    "Dart Container Corp." },
    {   VID(339)    "Livingston & Co., Inc." },
    {   VID(340)    "Alfa Laval LKM as" },
    {   VID(341)    "BF ENTRON Ltd. (British Federal)" },
    {   VID(342)    "Bekaert Engineering NV" },
    {   VID(343)    "Ferran  Scientific Inc." },
    {   VID(344)    "KEBA AG" },
    {   VID(345)    "Endress + Hauser" },
    {   VID(346)    "Reserved" },
    {   VID(347)    "ABB ALSTOM Power UK Ltd. (EGT)" },
    {   VID(348)    "Berger Lahr GmbH" },
    {   VID(349)    "Reserved" },
    {   VID(350)    "Federal Signal Corp." },
    {   VID(351)    "Kawasaki Robotics (USA), Inc." },
    {   VID(352)    "Bently Nevada Corporation" },
    {   VID(353)    "Reserved" },
    {   VID(354)    "FRABA Posital GmbH" },
    {   VID(355)    "Elsag Bailey, Inc." },
    {   VID(356)    "Fanuc Robotics America" },
    {   VID(357)    "Reserved" },
    {   VID(358)    "Surface Combustion, Inc." },
    {   VID(359)    "Reserved" },
    {   VID(360)    "AILES Electronics Ind. Co., Ltd." },
    {   VID(361)    "Wonderware Corporation" },
    {   VID(362)    "Particle Measuring Systems, Inc." },
    {   VID(363)    "Reserved" },
    {   VID(364)    "Reserved" },
    {   VID(365)    "BITS Co., Ltd" },
    {   VID(366)    "Japan Aviation Electronics Industry Ltd" },
    {   VID(367)    "Keyence Corporation" },
    {   VID(368)    "Kuroda Precision Industries Ltd." },
    {   VID(369)    "Mitsubishi Electric Semiconductor Application" },
    {   VID(370)    "Nippon Seisen Cable, Ltd." },
    {   VID(371)    "Omron ASO Co., Ltd" },
    {   VID(372)    "Seiko Seiki Co., Ltd." },
    {   VID(373)    "Sumitomo Heavy Industries, Ltd." },
    {   VID(374)    "Tango Computer Service Corporation" },
    {   VID(375)    "Technology Service, Inc." },
    {   VID(376)    "Toshiba Information Systems (Japan) Corporation" },
    {   VID(377)    "TOSHIBA Schneider Inverter Corporation" },
    {   VID(378)    "Toyooki Kogyo Co., Ltd." },
    {   VID(379)    "XEBEC" },
    {   VID(380)    "Madison Cable Corporation" },
    {   VID(381)    "Hitati Engineering & Services Co., Ltd" },
    {   VID(382)    "TEM-TECH Lab Co., Ltd" },
    {   VID(383)    "International Laboratory Corporation" },
    {   VID(384)    "Dyadic Systems Co., Ltd." },
    {   VID(385)    "SETO Electronics Industry Co., Ltd" },
    {   VID(386)    "Tokyo Electron Kyushu Limited" },
    {   VID(387)    "KEI System Co., Ltd" },
    {   VID(388)    "Reserved" },
    {   VID(389)    "Asahi Engineering Co., Ltd" },
    {   VID(390)    "Contrex Inc." },
    {   VID(391)    "Paradigm Controls Ltd." },
    {   VID(392)    "Reserved" },
    {   VID(393)    "Ohm Electric Co., Ltd." },
    {   VID(394)    "RKC Instrument Inc." },
    {   VID(395)    "Suzuki Motor Corporation" },
    {   VID(396)    "Custom Servo Motors Inc." },
    {   VID(397)    "PACE Control Systems" },
    {   VID(398)    "Reserved" },
    {   VID(399)    "Reserved" },
    {   VID(400)    "LINTEC Co., Ltd." },
    {   VID(401)    "Hitachi Cable Ltd." },
    {   VID(402)    "BUSWARE Direct" },
    {   VID(403)    "Eaton Electric B.V. (former Holec Holland N.V.)" },
    {   VID(404)    "VAT Vakuumventile AG" },
    {   VID(405)    "Scientific Technologies Incorporated" },
    {   VID(406)    "Alfa Instrumentos Eletronicos Ltda" },
    {   VID(407)    "TWK Elektronik GmbH" },
    {   VID(408)    "ABB Welding Systems AB" },
    {   VID(409)    "BYSTRONIC Maschinen AG" },
    {   VID(410)    "Kimura Electric Co., Ltd" },
    {   VID(411)    "Nissei Plastic Industrial Co., Ltd" },
    {   VID(412)    "Reserved" },
    {   VID(413)    "Kistler-Morse Corporation" },
    {   VID(414)    "Proteous Industries Inc." },
    {   VID(415)    "IDC Corporation" },
    {   VID(416)    "Nordson Corporation" },
    {   VID(417)    "Rapistan Systems" },
    {   VID(418)    "LP-Elektronik GmbH" },
    {   VID(419)    "GERBI & FASE S.p.A.(Fase Saldatura)" },
    {   VID(420)    "Phoenix Digital Corporation" },
    {   VID(421)    "Z-World Engineering" },
    {   VID(422)    "Honda R&D Co., Ltd." },
    {   VID(423)    "Bionics Instrument Co., Ltd." },
    {   VID(424)    "Teknic, Inc." },
    {   VID(425)    "R.Stahl, Inc." },
    {   VID(426)    "Reserved" },
    {   VID(427)    "Ryco Graphic Manufacturing Inc." },
    {   VID(428)    "Giddings & Lewis, Inc." },
    {   VID(429)    "Koganei Corporation" },
    {   VID(430)    "Reserved" },
    {   VID(431)    "Nichigoh Communication Electric Wire Co., Ltd." },
    {   VID(432)    "Reserved" },
    {   VID(433)    "Fujikura Ltd." },
    {   VID(434)    "AD Link Technology Inc." },
    {   VID(435)    "StoneL Corporation" },
    {   VID(436)    "Computer Optical Products, Inc." },
    {   VID(437)    "CONOS Inc." },
    {   VID(438)    "Erhardt + Leimer GmbH" },
    {   VID(439)    "UNIQUE Co. Ltd" },
    {   VID(440)    "Roboticsware, Inc." },
    {   VID(441)    "Nachi Fujikoshi Corporation" },
    {   VID(442)    "Hengstler GmbH" },
    {   VID(443)    "Reserved" },
    {   VID(444)    "SUNNY GIKEN Inc." },
    {   VID(445)    "Lenze Drive Systems GmbH" },
    {   VID(446)    "CD Systems B.V." },
    {   VID(447)    "FMT/Aircraft Gate Support Systems AB" },
    {   VID(448)    "Axiomatic Technologies Corp" },
    {   VID(449)    "Embedded System Products, Inc." },
    {   VID(450)    "Reserved" },
    {   VID(451)    "Mencom Corporation" },
    {   VID(452)    "Reserved" },
    {   VID(453)    "Matsushita Welding Systems Co., Ltd." },
    {   VID(454)    "Dengensha Mfg. Co. Ltd." },
    {   VID(455)    "Quinn Systems Ltd." },
    {   VID(456)    "Tellima Technology Ltd" },
    {   VID(457)    "MDT, Software" },
    {   VID(458)    "Taiwan Keiso Co., Ltd" },
    {   VID(459)    "Pinnacle Systems" },
    {   VID(460)    "Ascom Hasler Mailing Sys" },
    {   VID(461)    "INSTRUMAR Limited" },
    {   VID(462)    "Reserved" },
    {   VID(463)    "Navistar International Transportation Corp" },
    {   VID(464)    "Huettinger Elektronik GmbH + Co. KG" },
    {   VID(465)    "OCM Technology Inc." },
    {   VID(466)    "Professional Supply Inc." },
    {   VID(467)    "Control Solutions" },
    {   VID(468)    "Baumer IVO GmbH & Co. KG" },
    {   VID(469)    "Worcester Controls Corporation" },
    {   VID(470)    "Pyramid Technical Consultants, Inc." },
    {   VID(471)    "Reserved" },
    {   VID(472)    "Apollo Fire Detectors Limited" },
    {   VID(473)    "Avtron Manufacturing, Inc." },
    {   VID(474)    "Reserved" },
    {   VID(475)    "Tokyo Keiso Co., Ltd." },
    {   VID(476)    "Daishowa Swiki Co., Ltd." },
    {   VID(477)    "Kojima Instruments Inc." },
    {   VID(478)    "Shimadzu Corporation" },
    {   VID(479)    "Tatsuta Electric Wire & Cable Co., Ltd." },
    {   VID(480)    "MECS Corporation" },
    {   VID(481)    "Tahara Electric" },
    {   VID(482)    "Koyo Electronics" },
    {   VID(483)    "Clever Devices" },
    {   VID(484)    "GCD Hardware & Software GmbH" },
    {   VID(485)    "Reserved" },
    {   VID(486)    "Miller Electric Mfg Co." },
    {   VID(487)    "GEA Tuchenhagen GmbH" },
    {   VID(488)    "Riken Keiki Co., LTD" },
    {   VID(489)    "Keisokugiken Corporation" },
    {   VID(490)    "Fuji Machine Mfg. Co., Ltd" },
    {   VID(491)    "Reserved" },
    {   VID(492)    "Nidec-Shimpo Corp." },
    {   VID(493)    "UTEC Corporation" },
    {   VID(494)    "Sanyo Electric Co. Ltd." },
    {   VID(495)    "Reserved" },
    {   VID(496)    "Reserved" },
    {   VID(497)    "Okano Electric Wire Co. Ltd" },
    {   VID(498)    "Shimaden Co. Ltd." },
    {   VID(499)    "Teddington Controls Ltd" },
    {   VID(500)    "Reserved" },
    {   VID(501)    "VIPA GmbH" },
    {   VID(502)    "Warwick Manufacturing Group" },
    {   VID(503)    "Danaher Controls" },
    {   VID(504)    "Reserved" },
    {   VID(505)    "Reserved" },
    {   VID(506)    "American Science & Engineering" },
    {   VID(507)    "Accutron Controls International Inc." },
    {   VID(508)    "Norcott Technologies Ltd" },
    {   VID(509)    "TB Woods, Inc" },
    {   VID(510)    "Proportion-Air, Inc." },
    {   VID(511)    "SICK Stegmann GmbH" },
    {   VID(512)    "Reserved" },
    {   VID(513)    "Edwards Signaling" },
    {   VID(514)    "Sumitomo Metal Industries, Ltd" },
    {   VID(515)    "Cosmo Instruments Co., Ltd." },
    {   VID(516)    "Denshosha Co., Ltd." },
    {   VID(517)    "Kaijo Corp." },
    {   VID(518)    "Michiproducts Co., Ltd." },
    {   VID(519)    "Miura Corporation" },
    {   VID(520)    "TG Information Network Co., Ltd." },
    {   VID(521)    "Fujikin , Inc." },
    {   VID(522)    "Estic Corp." },
    {   VID(523)    "GS Hydraulic Sales" },
    {   VID(524)    "Reserved" },
    {   VID(525)    "MTE Limited" },
    {   VID(526)    "Hyde Park Electronics, Inc." },
    {   VID(527)    "Pfeiffer Vacuum GmbH" },
    {   VID(528)    "Cyberlogic Technologies" },
    {   VID(529)    "OKUMA Corporation FA Systems Division" },
    {   VID(530)    "Reserved" },
    {   VID(531)    "Hitachi Kokusai Electric Co., Ltd." },
    {   VID(532)    "SHINKO TECHNOS Co., Ltd." },
    {   VID(533)    "Itoh Electric Co., Ltd." },
    {   VID(534)    "Colorado Flow Tech Inc." },
    {   VID(535)    "Love Controls Division/Dwyer Inst." },
    {   VID(536)    "Alstom Drives and Controls" },
    {   VID(537)    "The Foxboro Company" },
    {   VID(538)    "Tescom Corporation" },
    {   VID(539)    "Reserved" },
    {   VID(540)    "Atlas Copco Controls UK" },
    {   VID(541)    "Reserved" },
    {   VID(542)    "Autojet Technologies" },
    {   VID(543)    "Prima Electronics S.p.A." },
    {   VID(544)    "PMA GmbH" },
    {   VID(545)    "Shimafuji Electric Co., Ltd" },
    {   VID(546)    "Oki Electric Industry Co., Ltd" },
    {   VID(547)    "Kyushu Matsushita Electric Co., Ltd" },
    {   VID(548)    "Nihon Electric Wire & Cable Co., Ltd" },
    {   VID(549)    "Tsuken Electric Ind Co., Ltd" },
    {   VID(550)    "Tamadic Co." },
    {   VID(551)    "MAATEL SA" },
    {   VID(552)    "OKUMA America" },
    {   VID(553)    "Control Techniques PLC-NA" },
    {   VID(554)    "TPC Wire & Cable" },
    {   VID(555)    "ATI Industrial Automation" },
    {   VID(556)    "Microcontrol (Australia) Pty Ltd" },
    {   VID(557)    "Serra Soldadura, S.A." },
    {   VID(558)    "Southwest Research Institute" },
    {   VID(559)    "Cabinplant International" },
    {   VID(560)    "Sartorius Mechatronics T&H GmbH" },
    {   VID(561)    "Comau S.p.A. Robotics & Final Assembly Division" },
    {   VID(562)    "Phoenix Contact" },
    {   VID(563)    "Yokogawa MAT Corporation" },
    {   VID(564)    "asahi sangyo co., ltd." },
    {   VID(565)    "Reserved" },
    {   VID(566)    "Akita Myotoku Ltd." },
    {   VID(567)    "OBARA Corp." },
    {   VID(568)    "Suetron Electronic GmbH" },
    {   VID(569)    "Reserved" },
    {   VID(570)    "Serck Controls Limited" },
    {   VID(571)    "Fairchild Industrial Products Company" },
    {   VID(572)    "ARO S.A." },
    {   VID(573)    "M2C GmbH" },
    {   VID(574)    "Shin Caterpillar Mitsubishi Ltd." },
    {   VID(575)    "Santest Co., Ltd." },
    {   VID(576)    "Cosmotechs Co., Ltd." },
    {   VID(577)    "Hitachi Electric Systems" },
    {   VID(578)    "Smartscan Ltd" },
    {   VID(579)    "Woodhead Software & Electronics France" },
    {   VID(580)    "Athena Controls, Inc." },
    {   VID(581)    "Syron Engineering & Manufacturing, Inc." },
    {   VID(582)    "Asahi Optical Co., Ltd." },
    {   VID(583)    "Sansha Electric Mfg. Co., Ltd." },
    {   VID(584)    "Nikki Denso Co., Ltd." },
    {   VID(585)    "Star Micronics, Co., Ltd." },
    {   VID(586)    "Ecotecnia Socirtat Corp." },
    {   VID(587)    "AC Technology Corp." },
    {   VID(588)    "West Instruments Limited" },
    {   VID(589)    "NTI Limited" },
    {   VID(590)    "Delta Computer Systems, Inc." },
    {   VID(591)    "FANUC Ltd." },
    {   VID(592)    "Hearn-Gu Lee" },
    {   VID(593)    "ABB Automation Products" },
    {   VID(594)    "Orion Machinery Co., Ltd." },
    {   VID(595)    "Reserved" },
    {   VID(596)    "Wire-Pro, Inc." },
    {   VID(597)    "Beijing Huakong Technology Co. Ltd." },
    {   VID(598)    "Yokoyama Shokai Co., Ltd." },
    {   VID(599)    "Toyogiken Co., Ltd." },
    {   VID(600)    "Coester Equipamentos Eletronicos Ltda." },
    {   VID(601)    "Reserved" },
    {   VID(602)    "Electroplating Engineers of Japan Ltd." },
    {   VID(603)    "ROBOX S.p.A." },
    {   VID(604)    "Spraying Systems Company" },
    {   VID(605)    "Benshaw Inc." },
    {   VID(606)    "ZPA-DP A.S." },
    {   VID(607)    "Wired Rite Systems" },
    {   VID(608)    "Tandis Research, Inc." },
    {   VID(609)    "SSD Drives GmbH" },
    {   VID(610)    "ULVAC Japan Ltd." },
    {   VID(611)    "DYNAX Corporation" },
    {   VID(612)    "Nor-Cal Products, Inc." },
    {   VID(613)    "Aros Electronics AB" },
    {   VID(614)    "Jun-Tech Co., Ltd." },
    {   VID(615)    "HAN-MI Co. Ltd." },
    {   VID(616)    "uniNtech (formerly SungGi Internet)" },
    {   VID(617)    "Hae Pyung Electronics Reserch Institute" },
    {   VID(618)    "Milwaukee Electronics" },
    {   VID(619)    "OBERG Industries" },
    {   VID(620)    "Parker Hannifin/Compumotor Division" },
    {   VID(621)    "TECHNO DIGITAL CORPORATION" },
    {   VID(622)    "Network Supply Co., Ltd." },
    {   VID(623)    "Union Electronics Co., Ltd." },
    {   VID(624)    "Tritronics Services PM Ltd." },
    {   VID(625)    "Rockwell Automation-Sprecher+Schuh" },
    {   VID(626)    "Matsushita Electric Industrial Co., Ltd/Motor Co." },
    {   VID(627)    "Rolls-Royce Energy Systems, Inc." },
    {   VID(628)    "JEONGIL INTERCOM CO., LTD" },
    {   VID(629)    "Interroll Corp." },
    {   VID(630)    "Hubbell Wiring Device-Kellems (Delaware)" },
    {   VID(631)    "Intelligent Motion Systems" },
    {   VID(632)    "Reserved" },
    {   VID(633)    "INFICON AG" },
    {   VID(634)    "Hirschmann, Inc." },
    {   VID(635)    "The Siemon Company" },
    {   VID(636)    "YAMAHA Motor Co. Ltd." },
    {   VID(637)    "aska corporation" },
    {   VID(638)    "Woodhead Connectivity" },
    {   VID(639)    "Trimble AB" },
    {   VID(640)    "Murrelektronik GmbH" },
    {   VID(641)    "Creatrix Labs, Inc." },
    {   VID(642)    "TopWorx" },
    {   VID(643)    "Kumho Industrial Co., Ltd." },
    {   VID(644)    "Wind River Systems, Inc." },
    {   VID(645)    "Bihl & Wiedemann GmbH" },
    {   VID(646)    "Harmonic Drive Systems Inc." },
    {   VID(647)    "Rikei Corporation" },
    {   VID(648)    "BL Autotec, Ltd." },
    {   VID(649)    "Hana Information & Technology Co., Ltd." },
    {   VID(650)    "Seoil Electric Co., Ltd." },
    {   VID(651)    "Fife Corporation" },
    {   VID(652)    "Shanghai Electrical Apparatus Research Institute" },
    {   VID(653)    "Reserved" },
    {   VID(654)    "Parasense Development Centre" },
    {   VID(655)    "Reserved" },
    {   VID(656)    "Reserved" },
    {   VID(657)    "Six Tau S.p.A." },
    {   VID(658)    "Aucos GmbH" },
    {   VID(659)    "Rotork Controls" },
    {   VID(660)    "Automationdirect.com" },
    {   VID(661)    "Thermo BLH" },
    {   VID(662)    "System Controls, Ltd." },
    {   VID(663)    "Univer S.p.A." },
    {   VID(664)    "MKS-Tenta Technology" },
    {   VID(665)    "Lika Electronic SNC" },
    {   VID(666)    "Mettler-Toledo, Inc." },
    {   VID(667)    "DXL USA Inc." },
    {   VID(668)    "Rockwell Automation/Entek IRD Intl." },
    {   VID(669)    "Nippon Otis Elevator Company" },
    {   VID(670)    "Sinano Electric, Co., Ltd." },
    {   VID(671)    "Sony Manufacturing Systems" },
    {   VID(672)    "Reserved" },
    {   VID(673)    "Contec Co., Ltd." },
    {   VID(674)    "Automated Solutions" },
    {   VID(675)    "Controlweigh" },
    {   VID(676)    "Reserved" },
    {   VID(677)    "Fincor Electronics" },
    {   VID(678)    "Cognex Corporation" },
    {   VID(679)    "Qualiflow" },
    {   VID(680)    "Weidmuller, Inc." },
    {   VID(681)    "Morinaga Milk Industry Co., Ltd." },
    {   VID(682)    "Takagi Industrial Co., Ltd." },
    {   VID(683)    "Wittenstein AG" },
    {   VID(684)    "Sena Technologies, Inc." },
    {   VID(685)    "Reserved" },
    {   VID(686)    "APV Products Unna" },
    {   VID(687)    "Creator Teknisk Utvedkling AB" },
    {   VID(688)    "Reserved" },
    {   VID(689)    "Mibu Denki Industrial Co., Ltd." },
    {   VID(690)    "Takamastsu Machineer Section" },
    {   VID(691)    "Startco Engineering Ltd." },
    {   VID(692)    "Reserved" },
    {   VID(693)    "Holjeron" },
    {   VID(694)    "ALCATEL High Vacuum Technology" },
    {   VID(695)    "Taesan LCD Co., Ltd." },
    {   VID(696)    "POSCON" },
    {   VID(697)    "VMIC" },
    {   VID(698)    "Matsushita Electric Works, Ltd." },
    {   VID(699)    "IAI Corporation" },
    {   VID(700)    "Horst GmbH" },
    {   VID(701)    "MicroControl GmbH & Co." },
    {   VID(702)    "Leine & Linde AB" },
    {   VID(703)    "Reserved" },
    {   VID(704)    "EC Elettronica Srl" },
    {   VID(705)    "VIT Software HB" },
    {   VID(706)    "Bronkhorst High-Tech B.V." },
    {   VID(707)    "Optex Co., Ltd." },
    {   VID(708)    "Yosio Electronic Co." },
    {   VID(709)    "Terasaki Electric Co., Ltd." },
    {   VID(710)    "Sodick Co., Ltd." },
    {   VID(711)    "MTS Systems Corporation-Automation Division" },
    {   VID(712)    "Mesa Systemtechnik" },
    {   VID(713)    "SHIN HO SYSTEM Co., Ltd." },
    {   VID(714)    "Goyo Electronics Co, Ltd." },
    {   VID(715)    "Loreme" },
    {   VID(716)    "SAB Brockskes GmbH & Co. KG" },
    {   VID(717)    "Trumpf Laser GmbH + Co. KG" },
    {   VID(718)    "Niigata Electronic Instruments Co., Ltd." },
    {   VID(719)    "Yokogawa Digital Computer Corporation" },
    {   VID(720)    "O.N. Electronic Co., Ltd." },
    {   VID(721)    "Industrial Control  Communication, Inc." },
    {   VID(722)    "ABB, Inc." },
    {   VID(723)    "ElectroWave USA, Inc." },
    {   VID(724)    "Industrial Network Controls, LLC" },
    {   VID(725)    "KDT Systems Co., Ltd." },
    {   VID(726)    "SEFA Technology Inc." },
    {   VID(727)    "Nippon POP Rivets and Fasteners Ltd." },
    {   VID(728)    "Yamato Scale Co., Ltd." },
    {   VID(729)    "Zener Electric" },
    {   VID(730)    "GSE Scale Systems" },
    {   VID(731)    "ISAS (Integrated Switchgear & Sys. Pty Ltd)" },
    {   VID(732)    "Beta LaserMike Limited" },
    {   VID(733)    "TOEI Electric Co., Ltd." },
    {   VID(734)    "Hakko Electronics Co., Ltd" },
    {   VID(735)    "Reserved" },
    {   VID(736)    "RFID, Inc." },
    {   VID(737)    "Adwin Corporation" },
    {   VID(738)    "Osaka Vacuum, Ltd." },
    {   VID(739)    "A-Kyung Motion, Inc." },
    {   VID(740)    "Camozzi S.P. A." },
    {   VID(741)    "Crevis Co., LTD" },
    {   VID(742)    "Rice Lake Weighing Systems" },
    {   VID(743)    "Linux Network Services" },
    {   VID(744)    "KEB Antriebstechnik GmbH" },
    {   VID(745)    "Hagiwara Electric Co., Ltd." },
    {   VID(746)    "Glass Inc. International" },
    {   VID(747)    "Reserved" },
    {   VID(748)    "DVT Corporation" },
    {   VID(749)    "Woodward Governor" },
    {   VID(750)    "Mosaic Systems, Inc." },
    {   VID(751)    "Laserline GmbH" },
    {   VID(752)    "COM-TEC, Inc." },
    {   VID(753)    "Weed Instrument" },
    {   VID(754)    "Prof-face European Technology Center" },
    {   VID(755)    "Fuji Automation Co., Ltd." },
    {   VID(756)    "Matsutame Co., Ltd." },
    {   VID(757)    "Hitachi Via Mechanics, Ltd." },
    {   VID(758)    "Dainippon Screen Mfg. Co. Ltd." },
    {   VID(759)    "FLS Automation A/S" },
    {   VID(760)    "ABB Stotz Kontakt GmbH" },
    {   VID(761)    "Technical Marine Service" },
    {   VID(762)    "Advanced Automation Associates, Inc." },
    {   VID(763)    "Baumer Ident GmbH" },
    {   VID(764)    "Tsubakimoto Chain Co." },
    {   VID(765)    "Reserved" },
    {   VID(766)    "Furukawa Co., Ltd." },
    {   VID(767)    "Active Power" },
    {   VID(768)    "CSIRO Mining Automation" },
    {   VID(769)    "Matrix Integrated Systems" },
    {   VID(770)    "Digitronic Automationsanlagen GmbH" },
    {   VID(771)    "SICK STEGMANN Inc." },
    {   VID(772)    "TAE-Antriebstechnik GmbH" },
    {   VID(773)    "Electronic Solutions" },
    {   VID(774)    "Rocon L.L.C." },
    {   VID(775)    "Dijitized Communications Inc." },
    {   VID(776)    "Asahi Organic Chemicals Industry Co., Ltd." },
    {   VID(777)    "Hodensha" },
    {   VID(778)    "Harting, Inc. NA" },
    {   VID(779)    "Kubler GmbH" },
    {   VID(780)    "Yamatake Corporation" },
    {   VID(781)    "JEOL" },
    {   VID(782)    "Yamatake Industrial Systems Co., Ltd." },
    {   VID(783)    "HAEHNE Elektronische Messgerate GmbH" },
    {   VID(784)    "Ci Technologies Pty Ltd (for Pelamos Industries)" },
    {   VID(785)    "N. SCHLUMBERGER & CIE" },
    {   VID(786)    "Teijin Seiki Co., Ltd." },
    {   VID(787)    "DAIKIN Industries, Ltd" },
    {   VID(788)    "RyuSyo Industrial Co., Ltd." },
    {   VID(789)    "SAGINOMIYA SEISAKUSHO, INC." },
    {   VID(790)    "Seishin Engineering Co., Ltd." },
    {   VID(791)    "Japan Support System Ltd." },
    {   VID(792)    "Decsys" },
    {   VID(793)    "Metronix Messgerate u. Elektronik GmbH" },
    {   VID(794)    "Reserved" },
    {   VID(795)    "Vaccon Company, Inc." },
    {   VID(796)    "Siemens Energy & Automation, Inc." },
    {   VID(797)    "Ten X Technology, Inc." },
    {   VID(798)    "Tyco Electronics" },
    {   VID(799)    "Delta Power Electronics Center" },
    {   VID(800)    "Denker" },
    {   VID(801)    "Autonics Corporation" },
    {   VID(802)    "JFE Electronic Engineering Pty. Ltd." },
    {   VID(803)    "Reserved" },
    {   VID(804)    "Electro-Sensors, Inc." },
    {   VID(805)    "Digi International, Inc." },
    {   VID(806)    "Texas Instruments" },
    {   VID(807)    "ADTEC Plasma Technology Co., Ltd" },
    {   VID(808)    "SICK AG" },
    {   VID(809)    "Ethernet Peripherals, Inc." },
    {   VID(810)    "Animatics Corporation" },
    {   VID(811)    "Reserved" },
    {   VID(812)    "Process Control Corporation" },
    {   VID(813)    "SystemV. Inc." },
    {   VID(814)    "Danaher Motion SRL" },
    {   VID(815)    "SHINKAWA Sensor Technology, Inc." },
    {   VID(816)    "Tesch GmbH & Co. KG" },
    {   VID(817)    "Reserved" },
    {   VID(818)    "Trend Controls Systems Ltd." },
    {   VID(819)    "Guangzhou ZHIYUAN Electronic Co., Ltd." },
    {   VID(820)    "Mykrolis Corporation" },
    {   VID(821)    "Bethlehem Steel Corporation" },
    {   VID(822)    "KK ICP" },
    {   VID(823)    "Takemoto Denki Corporation" },
    {   VID(824)    "The Montalvo Corporation" },
    {   VID(825)    "Reserved" },
    {   VID(826)    "LEONI Special Cables GmbH" },
    {   VID(827)    "Reserved" },
    {   VID(828)    "ONO SOKKI CO.,LTD." },
    {   VID(829)    "Rockwell Samsung Automation" },
    {   VID(830)    "SHINDENGEN ELECTRIC MFG. CO. LTD" },
    {   VID(831)    "Origin Electric Co. Ltd." },
    {   VID(832)    "Quest Technical Solutions, Inc." },
    {   VID(833)    "LS Cable, Ltd." },
    {   VID(834)    "Enercon-Nord Electronic GmbH" },
    {   VID(835)    "Northwire Inc." },
    {   VID(836)    "Engel Elektroantriebe GmbH" },
    {   VID(837)    "The Stanley Works" },
    {   VID(838)    "Celesco Transducer Products, Inc." },
    {   VID(839)    "Chugoku Electric Wire and Cable Co." },
    {   VID(840)    "Kongsberg Simrad AS" },
    {   VID(841)    "Panduit Corporation" },
    {   VID(842)    "Spellman High Voltage Electronics Corp." },
    {   VID(843)    "Kokusai Electric Alpha Co., Ltd." },
    {   VID(844)    "Brooks Automation, Inc." },
    {   VID(845)    "ANYWIRE CORPORATION" },
    {   VID(846)    "Honda Electronics Co. Ltd" },
    {   VID(847)    "REO Elektronik AG" },
    {   VID(848)    "Fusion UV Systems, Inc." },
    {   VID(849)    "ASI Advanced Semiconductor Instruments GmbH" },
    {   VID(850)    "Datalogic, Inc." },
    {   VID(851)    "SoftPLC Corporation" },
    {   VID(852)    "Dynisco Instruments LLC" },
    {   VID(853)    "WEG Industrias SA" },
    {   VID(854)    "Frontline Test Equipment, Inc." },
    {   VID(855)    "Tamagawa Seiki Co., Ltd." },
    {   VID(856)    "Multi Computing Co., Ltd." },
    {   VID(857)    "RVSI" },
    {   VID(858)    "Commercial Timesharing Inc." },
    {   VID(859)    "Tennessee Rand Automation LLC" },
    {   VID(860)    "Wacogiken Co., Ltd" },
    {   VID(861)    "Reflex Integration Inc." },
    {   VID(862)    "Siemens AG, A&D PI Flow Instruments" },
    {   VID(863)    "G. Bachmann Electronic GmbH" },
    {   VID(864)    "NT International" },
    {   VID(865)    "Schweitzer Engineering Laboratories" },
    {   VID(866)    "ATR Industrie-Elektronik GmbH Co." },
    {   VID(867)    "PLASMATECH Co., Ltd" },
    {   VID(868)    "Reserved" },
    {   VID(869)    "GEMU GmbH & Co. KG" },
    {   VID(870)    "Alcorn McBride Inc." },
    {   VID(871)    "MORI SEIKI CO., LTD" },
    {   VID(872)    "NodeTech Systems Ltd" },
    {   VID(873)    "Emhart Teknologies" },
    {   VID(874)    "Cervis, Inc." },
    {   VID(875)    "FieldServer Technologies (Div Sierra Monitor Corp)" },
    {   VID(876)    "NEDAP Power Supplies" },
    {   VID(877)    "Nippon Sanso Corporation" },
    {   VID(878)    "Mitomi Giken Co., Ltd." },
    {   VID(879)    "PULS GmbH" },
    {   VID(880)    "Reserved" },
    {   VID(881)    "Japan Control Engineering Ltd" },
    {   VID(882)    "Embedded Systems Korea (Former Zues Emtek Co Ltd.)" },
    {   VID(883)    "Automa SRL" },
    {   VID(884)    "Harms+Wende GmbH & Co KG" },
    {   VID(885)    "SAE-STAHL GmbH" },
    {   VID(886)    "Microwave Data Systems" },
    {   VID(887)    "Bernecker + Rainer Industrie-Elektronik GmbH" },
    {   VID(888)    "Hiprom Technologies" },
    {   VID(889)    "Reserved" },
    {   VID(890)    "Nitta Corporation" },
    {   VID(891)    "Kontron Modular Computers GmbH" },
    {   VID(892)    "Marlin Controls" },
    {   VID(893)    "ELCIS s.r.l." },
    {   VID(894)    "Acromag, Inc." },
    {   VID(895)    "Avery Weigh-Tronix" },
    {   VID(896)    "Reserved" },
    {   VID(897)    "Reserved" },
    {   VID(898)    "Reserved" },
    {   VID(899)    "Practicon Ltd" },
    {   VID(900)    "Schunk GmbH & Co. KG" },
    {   VID(901)    "MYNAH Technologies" },
    {   VID(902)    "Defontaine Groupe" },
    {   VID(903)    "Emerson Process Management Power & Water Solutions" },
    {   VID(904)    "F.A. Elec" },
    {   VID(905)    "Hottinger Baldwin Messtechnik GmbH" },
    {   VID(906)    "Coreco Imaging, Inc." },
    {   VID(907)    "London Electronics Ltd." },
    {   VID(908)    "HSD SpA" },
    {   VID(909)    "Comtrol Corporation" },
    {   VID(910)    "TEAM, S.A. (Tecnica Electronica de Automatismo Y Medida)" },
    {   VID(911)    "MAN B&W Diesel Ltd. Regulateurs Europa" },
    {   VID(912)    "Reserved" },
    {   VID(913)    "Reserved" },
    {   VID(914)    "Micro Motion, Inc." },
    {   VID(915)    "Eckelmann AG" },
    {   VID(916)    "Hanyoung Nux" },
    {   VID(917)    "Ransburg Industrial Finishing KK" },
    {   VID(918)    "Kun Hung Electric Co. Ltd." },
    {   VID(919)    "Brimos wegbebakening b.v." },
    {   VID(920)    "Nitto Seiki Co., Ltd" },
    {   VID(921)    "PPT Vision, Inc." },
    {   VID(922)    "Yamazaki Machinery Works" },
    {   VID(923)    "SCHMIDT Technology GmbH" },
    {   VID(924)    "Parker Hannifin SpA (SBC Division)" },
    {   VID(925)    "HIMA Paul Hildebrandt GmbH" },
    {   VID(926)    "RivaTek, Inc." },
    {   VID(927)    "Misumi Corporation" },
    {   VID(928)    "GE Multilin" },
    {   VID(929)    "Measurement Computing Corporation" },
    {   VID(930)    "Jetter AG" },
    {   VID(931)    "Tokyo Electronics Systems Corporation" },
    {   VID(932)    "Togami Electric Mfg. Co., Ltd." },
    {   VID(933)    "HK Systems" },
    {   VID(934)    "CDA Systems Ltd." },
    {   VID(935)    "Aerotech Inc." },
    {   VID(936)    "JVL Industrie Elektronik A/S" },
    {   VID(937)    "NovaTech Process Solutions LLC" },
    {   VID(938)    "Reserved" },
    {   VID(939)    "Cisco Systems" },
    {   VID(940)    "Grid Connect" },
    {   VID(941)    "ITW Automotive Finishing" },
    {   VID(942)    "HanYang System" },
    {   VID(943)    "ABB K.K. Technical Center" },
    {   VID(944)    "Taiyo Electric Wire & Cable Co., Ltd." },
    {   VID(945)    "Reserved" },
    {   VID(946)    "SEREN IPS INC" },
    {   VID(947)    "Belden CDT Electronics Division" },
    {   VID(948)    "ControlNet International" },
    {   VID(949)    "Gefran S.P.A." },
    {   VID(950)    "Jokab Safety AB" },
    {   VID(951)    "SUMITA OPTICAL GLASS, INC." },
    {   VID(952)    "Biffi Italia srl" },
    {   VID(953)    "Beck IPC GmbH" },
    {   VID(954)    "Copley Controls Corporation" },
    {   VID(955)    "Fagor Automation S. Coop." },
    {   VID(956)    "DARCOM" },
    {   VID(957)    "Frick Controls (div. of York International)" },
    {   VID(958)    "SymCom, Inc." },
    {   VID(959)    "Infranor" },
    {   VID(960)    "Kyosan Cable, Ltd." },
    {   VID(961)    "Varian Vacuum Technologies" },
    {   VID(962)    "Messung Systems" },
    {   VID(963)    "Xantrex Technology, Inc." },
    {   VID(964)    "StarThis Inc." },
    {   VID(965)    "Chiyoda Co., Ltd." },
    {   VID(966)    "Flowserve Corporation" },
    {   VID(967)    "Spyder Controls Corp." },
    {   VID(968)    "IBA AG" },
    {   VID(969)    "SHIMOHIRA ELECTRIC MFG.CO.,LTD" },
    {   VID(970)    "Reserved" },
    {   VID(971)    "Siemens L&A" },
    {   VID(972)    "Micro Innovations AG" },
    {   VID(973)    "Switchgear & Instrumentation" },
    {   VID(974)    "PRE-TECH CO., LTD." },
    {   VID(975)    "National Semiconductor" },
    {   VID(976)    "Invensys Process Systems" },
    {   VID(977)    "Ametek HDR Power Systems" },
    {   VID(978)    "Reserved" },
    {   VID(979)    "TETRA-K Corporation" },
    {   VID(980)    "C & M Corporation" },
    {   VID(981)    "Siempelkamp Maschinen" },
    {   VID(982)    "Reserved" },
    {   VID(983)    "Daifuku America Corporation" },
    {   VID(984)    "Electro-Matic Products Inc." },
    {   VID(985)    "BUSSAN MICROELECTRONICS CORP." },
    {   VID(986)    "ELAU AG" },
    {   VID(987)    "Hetronic USA" },
    {   VID(988)    "NIIGATA POWER SYSTEMS Co., Ltd." },
    {   VID(989)    "Software Horizons Inc." },
    {   VID(990)    "B3 Systems, Inc." },
    {   VID(991)    "Moxa Networking Co., Ltd." },
    {   VID(992)    "Reserved" },
    {   VID(993)    "S4 Integration" },
    {   VID(994)    "Elettro Stemi S.R.L." },
    {   VID(995)    "AquaSensors" },
    {   VID(996)    "Ifak System GmbH" },
    {   VID(997)    "SANKEI MANUFACTURING Co.,LTD." },
    {   VID(998)    "Emerson Network Power Co., Ltd." },
    {   VID(999)    "Fairmount Automation, Inc." },
    {   VID(1000)   "Bird Electronic Corporation" },
    {   VID(1001)   "Nabtesco Corporation" },
    {   VID(1002)   "AGM Electronics, Inc." },
    {   VID(1003)   "ARCX Inc." },
    {   VID(1004)   "DELTA I/O Co." },
    {   VID(1005)   "Chun IL Electric Ind. Co." },
    {   VID(1006)   "N-Tron" },
    {   VID(1007)   "Nippon Pneumatics/Fludics System CO.,LTD." },
    {   VID(1008)   "DDK Ltd." },
    {   VID(1009)   "Seiko Epson Corporation" },
    {   VID(1010)   "Halstrup-Walcher GmbH" },
    {   VID(1011)   "ITT" },
    {   VID(1012)   "Ground Fault Systems bv" },
    {   VID(1013)   "Scolari Engineering S.p.A." },
    {   VID(1014)   "Vialis Traffic bv" },
    {   VID(1015)   "Weidmueller Interface GmbH & Co. KG" },
    {   VID(1016)   "Shanghai Sibotech Automation Co. Ltd" },
    {   VID(1017)   "AEG Power Supply Systems GmbH" },
    {   VID(1018)   "Komatsu Electronics Inc." },
    {   VID(1019)   "Souriau" },
    {   VID(1020)   "Baumuller Chicago Corp." },
    {   VID(1021)   "J. Schmalz GmbH" },
    {   VID(1022)   "SEN Corporation" },
    {   VID(1023)   "Korenix Technology Co. Ltd" },
    {   VID(1024)   "Cooper Power Tools" },
    {   VID(1025)   "INNOBIS" },
    {   VID(1026)   "Shinho System" },
    {   VID(1027)   "Xm Services Ltd." },
    {   VID(1028)   "KVC Co., Ltd." },
    {   VID(1029)   "Sanyu Seiki Co., Ltd." },
    {   VID(1030)   "TuxPLC" },
    {   VID(1031)   "Northern Network Solutions" },
    {   VID(1032)   "Converteam GmbH" },
    {   VID(1033)   "Symbol Technologies" },
    {   VID(1034)   "S-TEAM Lab" },
    {   VID(1035)   "Maguire Products, Inc." },
    {   VID(1036)   "AC&T" },
    {   VID(1037)   "MITSUBISHI HEAVY INDUSTRIES, LTD. KOBE SHIPYARD & MACHINERY WORKS" },
    {   VID(1038)   "Hurletron Inc." },
    {   VID(1039)   "Chunichi Denshi Co., Ltd" },
    {   VID(1040)   "Cardinal Scale Mfg. Co." },
    {   VID(1041)   "BTR NETCOM via RIA Connect, Inc." },
    {   VID(1042)   "Base2" },
    {   VID(1043)   "ASRC Aerospace" },
    {   VID(1044)   "Beijing Stone Automation" },
    {   VID(1045)   "Changshu Switchgear Manufacture Ltd." },
    {   VID(1046)   "METRONIX Corp." },
    {   VID(1047)   "WIT" },
    {   VID(1048)   "ORMEC Systems Corp." },
    {   VID(1049)   "ASATech (China) Inc." },
    {   VID(1050)   "Controlled Systems Limited" },
    {   VID(1051)   "Mitsubishi Heavy Ind. Digital System Co., Ltd. (M.H.I.)" },
    {   VID(1052)   "Electrogrip" },
    {   VID(1053)   "TDS Automation" },
    {   VID(1054)   "T&C Power Conversion, Inc." },
    {   VID(1055)   "Robostar Co., Ltd" },
    {   VID(1056)   "Scancon A/S" },
    {   VID(1057)   "Haas Automation, Inc." },
    {   VID(1058)   "Eshed Technology" },
    {   VID(1059)   "Delta Electronic Inc." },
    {   VID(1060)   "Innovasic Semiconductor" },
    {   VID(1061)   "SoftDEL Systems Limited" },
    {   VID(1062)   "FiberFin, Inc." },
    {   VID(1063)   "Nicollet Technologies Corp." },
    {   VID(1064)   "B.F. Systems" },
    {   VID(1065)   "Empire Wire and Supply LLC" },
    {   VID(1066)   "Reserved" },
    {   VID(1067)   "Elmo Motion Control LTD" },
    {   VID(1068)   "Reserved" },
    {   VID(1069)   "Asahi Keiki Co., Ltd." },
    {   VID(1070)   "Joy Mining Machinery" },
    {   VID(1071)   "MPM Engineering Ltd" },
    {   VID(1072)   "Wolke Inks & Printers GmbH" },
    {   VID(1073)   "Mitsubishi Electric Engineering Co., Ltd." },
    {   VID(1074)   "COMET AG" },
    {   VID(1075)   "Real Time Objects & Systems, LLC" },
    {   VID(1076)   "MISCO Refractometer" },
    {   VID(1077)   "JT Engineering Inc." },
    {   VID(1078)   "Automated Packing Systems" },
    {   VID(1079)   "Niobrara R&D Corp." },
    {   VID(1080)   "Garmin Ltd." },
    {   VID(1081)   "Japan Mobile Platform Co., Ltd" },
    {   VID(1082)   "Advosol Inc." },
    {   VID(1083)   "ABB Global Services Limited" },
    {   VID(1084)   "Sciemetric Instruments Inc." },
    {   VID(1085)   "Tata Elxsi Ltd." },
    {   VID(1086)   "TPC Mechatronics, Co., Ltd." },
    {   VID(1087)   "Cooper Bussmann" },
    {   VID(1088)   "Trinite Automatisering B.V." },
    {   VID(1089)   "Peek Traffic B.V." },
    {   VID(1090)   "Acrison, Inc" },
    {   VID(1091)   "Applied Robotics, Inc." },
    {   VID(1092)   "FireBus Systems, Inc." },
    {   VID(1093)   "Beijing Sevenstar Huachuang Electronics" },
    {   VID(1094)   "Magnetek" },
    {   VID(1095)   "Microscan" },
    {   VID(1096)   "Air Water Inc." },
    {   VID(1097)   "Sensopart Industriesensorik GmbH" },
    {   VID(1098)   "Tiefenbach Control Systems GmbH" },
    {   VID(1099)   "INOXPA S.A" },
    {   VID(1100)   "Zurich University of Applied Sciences" },
    {   VID(1101)   "Ethernet Direct" },
    {   VID(1102)   "GSI-Micro-E Systems" },
    {   VID(1103)   "S-Net Automation Co., Ltd." },
    {   VID(1104)   "Power Electronics S.L." },
    {   VID(1105)   "Renesas Technology Corp." },
    {   VID(1106)   "NSWCCD-SSES" },
    {   VID(1107)   "Porter Engineering Ltd." },
    {   VID(1108)   "Meggitt Airdynamics, Inc." },
    {   VID(1109)   "Inductive Automation" },
    {   VID(1110)   "Neural ID" },
    {   VID(1111)   "EEPod LLC" },
    {   VID(1112)   "Hitachi Industrial Equipment Systems Co., Ltd." },
    {   VID(1113)   "Salem Automation" },
    {   VID(1114)   "port GmbH" },
    {   VID(1115)   "B & PLUS" },
    {   VID(1116)   "Graco Inc." },
    {   VID(1117)   "Altera Corporation" },
    {   VID(1118)   "Technology Brewing Corporation" },
    {   VID(1121)   "CSE Servelec" },
    {   VID(1124)   "Fluke Networks" },
    {   VID(1125)   "Tetra Pak Packaging Solutions SPA" },
    {   VID(1126)   "Racine Federated, Inc." },
    {   VID(1127)   "Pureron Japan Co., Ltd." },
    {   VID(1130)   "Brother Industries, Ltd." },
    {   VID(1132)   "Leroy Automation" },
    {   VID(1134)   "THK CO., LTD." },
    {   VID(1137)   "TR-Electronic GmbH" },
    {   VID(1138)   "ASCON S.p.A." },
    {   VID(1139)   "Toledo do Brasil Industria de Balancas Ltda." },
    {   VID(1140)   "Bucyrus DBT Europe GmbH" },
    {   VID(1141)   "Emerson Process Management Valve Automation" },
    {   VID(1142)   "Alstom Transport" },
    {   VID(1144)   "Matrox Electronic Systems" },
    {   VID(1145)   "Littelfuse" },
    {   VID(1146)   "PLASMART, Inc." },
    {   VID(1147)   "Miyachi Corporation" },
    {   VID(1150)   "Promess Incorporated" },
    {   VID(1151)   "COPA-DATA GmbH" },
    {   VID(1152)   "Precision Engine Controls Corporation" },
    {   VID(1153)   "Alga Automacao e controle LTDA" },
    {   VID(1154)   "U.I. Lapp GmbH" },
    {   VID(1155)   "ICES" },
    {   VID(1156)   "Philips Lighting bv" },
    {   VID(1157)   "Aseptomag AG" },
    {   VID(1158)   "ARC Informatique" },
    {   VID(1159)   "Hesmor GmbH" },
    {   VID(1160)   "Kobe Steel, Ltd." },
    {   VID(1161)   "FLIR Systems" },
    {   VID(1162)   "Simcon A/S" },
    {   VID(1163)   "COPALP" },
    {   VID(1164)   "Zypcom, Inc." },
    {   VID(1165)   "Swagelok" },
    {   VID(1166)   "Elspec" },
    {   VID(1167)   "ITT Water & Wastewater AB" },
    {   VID(1168)   "Kunbus GmbH Industrial Communication" },
    {   VID(1170)   "Performance Controls, Inc." },
    {   VID(1171)   "ACS Motion Control, Ltd." },
    {   VID(1173)   "IStar Technology Limited" },
    {   VID(1174)   "Alicat Scientific, Inc." },
    {   VID(1176)   "ADFweb.com SRL" },
    {   VID(1177)   "Tata Consultancy Services Limited" },
    {   VID(1178)   "CXR Ltd." },
    {   VID(1179)   "Vishay Nobel AB" },
    {   VID(1181)   "SolaHD" },
    {   VID(1182)   "Endress+Hauser" },
    {   VID(1183)   "Bartec GmbH" },
    {   VID(1185)   "AccuSentry, Inc." },
    {   VID(1186)   "Exlar Corporation" },
    {   VID(1187)   "ILS Technology" },
    {   VID(1188)   "Control Concepts Inc." },
    {   VID(1190)   "Procon Engineering Limited" },
    {   VID(1191)   "Hermary Opto Electronics Inc." },
    {   VID(1192)   "Q-Lambda" },
    {   VID(1194)   "VAMP Ltd" },
    {   VID(1195)   "FlexLink" },
    {   VID(1196)   "Office FA.com Co., Ltd." },
    {   VID(1197)   "SPMC (Changzhou) Co. Ltd." },
    {   VID(1198)   "Anton Paar GmbH" },
    {   VID(1199)   "Zhuzhou CSR Times Electric Co., Ltd." },
    {   VID(1200)   "DeStaCo" },
    {   VID(1201)   "Synrad, Inc" },
    {   VID(1202)   "Bonfiglioli Vectron GmbH" },
    {   VID(1203)   "Pivotal Systems" },
    {   VID(1204)   "TKSCT" },
    {   VID(1205)   "Randy Nuernberger" },
    {   VID(1206)   "CENTRALP" },
    {   VID(1207)   "Tengen Group" },
    {   VID(1208)   "OES, Inc." },
    {   VID(1209)   "Actel Corporation" },
    {   VID(1210)   "Monaghan Engineering, Inc." },
    {   VID(1211)   "wenglor sensoric gmbh" },
    {   VID(1212)   "HSA Systems" },
    {   VID(1213)   "MK Precision Co., Ltd." },
    {   VID(1214)   "Tappan Wire and Cable" },
    {   VID(1215)   "Heinzmann GmbH & Co. KG" },
    {   VID(1216)   "Process Automation International Ltd." },
    {   VID(1217)   "Secure Crossing" },
    {   VID(1218)   "SMA Railway Technology GmbH" },
    {   VID(1219)   "FMS Force Measuring Systems AG" },
    {   VID(1220)   "ABT Endustri Enerji Sistemleri Sanayi Tic. Ltd. Sti." },
    {   VID(1221)   "MagneMotion Inc." },
    {   VID(1222)   "STS Co., Ltd." },
    {   VID(1223)   "MERAK SIC, SA" },
    {   VID(1224)   "ABOUNDI, Inc." },
    {   VID(1225)   "Rosemount Inc." },
    {   VID(1226)   "GEA FES, Inc." },
    {   VID(1227)   "TMG Technologie und Engineering GmbH" },
    {   VID(1228)   "embeX GmbH" },
    {   VID(1229)   "GH Electrotermia, S.A." },
    {   VID(1230)   "Tolomatic" },
    {   VID(1231)   "Dukane" },
    {   VID(1232)   "Elco (Tian Jin) Electronics Co., Ltd." },
    {   VID(1233)   "Jacobs Automation" },
    {   VID(1234)   "Noda Radio Frequency Technologies Co., Ltd." },
    {   VID(1235)   "MSC Tuttlingen GmbH" },
    {   VID(1236)   "Hitachi Cable Manchester" },
    {   VID(1237)   "ACOREL SAS" },
    {   VID(1238)   "Global Engineering Solutions Co., Ltd." },
    {   VID(1239)   "ALTE Transportation, S.L." },
    {   VID(1240)   "Penko Engineering B.V." },

    // missing some here.

    {   VID(1251)   "Siemens" },
};


#define HAVE_BSEARCH    1

#define VENDOR_COUNT     int( sizeof(vendors)/sizeof(vendors[0]))


#if defined(HAVE_BSEARCH)

#include <stdlib.h>         // bsearch()

static int compare( const void* a1, const void* a2 )
{
    const VendorRow* v1 = (const VendorRow*) a1;
    const VendorRow* v2 = (const VendorRow*) a2;

    int ret = v1->id - v2->id;
    return ret;
}


const char* CipVendorStr( int aVendorId )
{
    static char buf[16];

    VendorRow search;

    search.id = aVendorId;

    const VendorRow* findings = (const VendorRow*) bsearch(
            &search,
            vendors, VENDOR_COUNT,
            sizeof(VendorRow), compare );

    if( findings )
        return findings->name;
    else
    {
        snprintf( buf, sizeof(buf), "%d", aVendorId );
        return buf;
    }
}


#else

const char* CipVendorStr( int aVendorId )
{
    static char buf[16];

    for( int i = 0; i < VENDOR_COUNT;  ++i )
    {
        if( vendors[i].id == aVendorId )
            return vendors[i].name;
    }

    snprintf( buf, sizeof(buf), "%d", aVendorId );

    return buf;
}

#endif


#if 0

#include <stdlib.h>

int main( int argc, char** argv )
{
#if 0
    for( int i =0; i < VENDOR_COUNT;  ++i )
    {
        if( vendors[i].id != i )
        {
            printf( "vendors[%d].id==%d\n", i, vendors[i].id );
        }
    }
#endif

    if( argc != 2 )
    {
        fprintf( stderr, "Usage: %s <vendor_id>\n", argv[0] );
        exit( 1 );
    }


    int id = strtoul( argv[1], NULL, 0 );

    printf( "id:%d  name:'%s'\n",  id, CipVendorStr( id ) );
}

#endif

